import * as THREE from './vendor/three.module.js';
import { RoomController } from './rooms.js?v=c0a15dbd0b32';
import { artworks } from './room-data.js?v=83c44b5c15ff';
const $=s=>document.querySelector(s);
const world=$('#world'),dialog=$('#project-dialog');
const rooms=new RoomController({onExit:()=>world.focus({preventScroll:true})});
const MAP_SCALE=Math.SQRT2;
const zoneInfo={community:{name:'LEVEL0 Clubhouse',x:-8,z:-3,anchorY:5},lab:{name:'CLAUDE × UNITY',x:2,z:-7,anchorY:6},arcade:{name:'Game Arcade',x:10,z:3,anchorY:5}};
Object.values(zoneInfo).forEach(z=>{z.x*=MAP_SCALE;z.z*=MAP_SCALE;z.anchorY*=MAP_SCALE;});
const visited=new Set();let activeZone=null,exploring=false,mapOverview=true;
function openZone(zone){activeZone=zone;visited.add(zone);document.querySelectorAll(`[data-zone="${zone}"]`).forEach(e=>e.classList.add('visited'));$('#visit-count').textContent=`${visited.size} / 3`;if(renderer){if(dialog.open)dialog.close();rooms.open(zone,reduced);}else{$('#dialog-content').innerHTML=panels[zone]();if(!dialog.open)dialog.showModal();dialog.scrollTop=0;}}
function projectIndex(items=artworks){return `<section class="project-index" aria-label="Selected projects"><div class="project-index-heading"><h3>Selected projects</h3><span>${items.length} projects · Choose a work</span></div><div class="project-index-grid">${items.map(a=>`<button class="project-index-card" data-project="${a.id}"><span class="project-index-number">${a.no}</span><span><strong>${a.title}</strong><small>${a.tools}</small><small>${a.type}</small></span><span aria-hidden="true">↗</span></button>`).join('')}</div></section>`;}
function openProject(id){const a=artworks.find(a=>a.id===id);if(!a)return;if(renderer){openZone('lab');rooms.activate(id);}else{$('#dialog-content').innerHTML=`<div class="panel-eyebrow">SELECTED WORK / ${a.no}</div><h2 id="dialog-title">${a.title}</h2><div class="tagline"><span>${a.type}</span><span>${a.tools}</span></div><figure class="project-preview">${rooms.artworkPreview(a,false)}</figure><p class="panel-lead">${a.description}</p>${links([[a.link,a.url]])}${foot('lab')}`;if(!dialog.open)dialog.showModal();dialog.scrollTop=0;}}
function overview(){$('#dialog-content').innerHTML=`<div class="panel-eyebrow">YUMIN'S BUILDER CAMPUS</div><h2 id="dialog-title">I build games.<br>And communities that build.</h2><p class="panel-lead">Yumin Kang · Computer Software, Daegu University<br>Game developer / Founder of LEVEL0</p>${projectIndex()}<div class="overview-grid">${Object.entries(zoneInfo).map(([id,z],i)=>`<button class="overview-card" data-zone="${id}"><span class="ov-num">0${i+1}</span><span><h3>${z.name}</h3><p>${['From finding teammates to six teams shipping their first jam games.','Using Claude Code and Unity MCP to inspect, build and debug in the editor.','Insert a coin to discover playable games and our first game jam.'][i]}</p></span><span>↗</span></button>`).join('')}</div><div class="panel-links"><a href="./yumin-builder-resume.pdf" download="Yumin_Kang_Resume.pdf">Resume PDF ↓</a><a class="secondary" href="https://github.com/yumin-beep" target="_blank" rel="noopener noreferrer">GitHub ↗</a><a class="secondary" href="https://app.notion.com/p/3d2cea20cae1813bba6bd6a084a4f183" target="_blank" rel="noopener noreferrer">Project archive ↗</a></div>`;if(!dialog.open)dialog.showModal();dialog.scrollTop=0;}
const links=(list)=>`<div class="panel-links">${list.map(([label,url],i)=>`<a href="${url}" target="_blank" rel="noopener noreferrer" class="${i?'secondary':''}">${label} <span>↗</span></a>`).join('')}</div>`;
const foot=(next)=>`<div class="panel-footer"><button data-overview>← All projects</button><button data-zone="${next}">Next space →</button></div>`;
const panels={
community:()=>`<div class="panel-eyebrow">01 / COMMUNITY · LEVEL0 CLUBHOUSE</div><h2 id="dialog-title">A place to find<br>your fellow builders.</h2><p class="panel-lead">I founded LEVEL0, a university game development club, and became its first president. I connected designers, artists and programmers, helping first-time makers take their projects through to completion.</p><div class="stats"><div><strong>~30</strong><span>Founding members</span></div><div><strong>6</strong><span>Teams in our first jam</span></div><div><strong>6</strong><span>Browser games submitted</span></div></div><section class="case"><h3>From recruitment to the first playtest</h3><p>I led recruitment, assigned roles and formed teams, using Discord, Notion and GitHub for collaboration. For our first game jam, I coordinated the schedule, exhibition, external judging and student voting. I also joined one of the development teams.</p></section><div class="steps"><article><b>01 · Connect</b><p>Bring designers, artists and programmers together into teams.</p></article><article><b>02 · Finish</b><p>All six teams submitted games that anyone could play in a browser.</p></article><article><b>03 · Grow</b><p>Help co-organize a regional game jam connecting eight universities.</p></article></div>${links([['Play the jam entries','https://itch.io/jam/level0-firstjam-gaenojam'],['Club records','https://app.notion.com/p/086cea20cae18291a3de016079ace80c']])}${foot('lab')}`,
lab:()=>`<div class="panel-eyebrow">02 / AI WORKSHOP <span class="badge">Prototype in development</span></div><h2 id="dialog-title">Building with Claude.<br>Debugging in the game.</h2><p class="panel-lead">For Job Battle, I defined the rules and art direction, then connected Claude Code to Unity MCP. I used the editor and live play-mode state to check what the code was actually doing.</p><div class="tagline"><span>Unity · C#</span><span>Photon</span><span>Claude Code</span><span>Unity MCP</span></div><section class="case"><h3>The code looked right. The character stayed still.</h3><p>Idle and Attack animation errors kept returning after fixes. Inspecting the player created at runtime revealed that its Animator had no controller assigned.</p></section><div class="steps"><article><b>Inspect the live state</b><p>Use Unity MCP to inspect the scene, console and runtime player’s Animator.</p></article><article><b>Fix the root cause</b><p>Change setup code to reuse the existing controller asset instead of deleting and recreating it.</p></article><article><b>Check in play mode</b><p>Confirm the controller assignment, Idle playback and entry into Attack.</p></article></div><div class="evidence"><h3>My decisions. Built and tested with Claude.</h3><p>I defined the four-player territory-control rules, practice bots, art direction and priorities. With Claude, I iterated on code, editor integration and debugging, then played the results and refined them.</p></div>${links([['Job Battle code','https://github.com/yumin-beep/3djobbattle'],['Development notes','https://app.notion.com/p/3d2cea20cae18105862feebd1f39055c']])}${projectIndex()}${foot('arcade')}`,
arcade:()=>`<div class="panel-eyebrow">03 / PLAYGROUND</div><h2 id="dialog-title">Less explaining.<br>More playing.</h2><p class="panel-lead">From browser races to deduction with local AI.<br>Ideas made into things you can play.</p><div class="project-pair"><article class="project-box"><span class="project-glyph">RACE / WEB GAME</span><h3>Lucky Derby</h3><p>A browser racing game with transformations, weather and cinematic camera work. Building with Claude, I refined the camera to keep the chasing horses in view.</p><div class="tagline"><span>Solo project</span><span>Three.js</span><span>JavaScript</span></div>${links([['Play now','https://yumin-beep.github.io/lucky-derby/'],['View code','https://github.com/yumin-beep/lucky-derby']])}</article><article class="project-box"><span class="project-glyph">DEDUCTION / LOCAL AI</span><h3>AI Mafia</h3><p>A deduction game prototype for one human and five local AI players. I developed the rules, prompts, UI and Ollama integration.</p><div class="tagline"><span>Team project</span><span>Unity · C#</span></div><p class="source-note">Development: Claude Code + Unity MCP<br>In-game AI: Ollama + Gemma</p>${links([['Making the game','https://app.notion.com/p/3d2cea20cae181909eb7cb4058ef9894'],['View code','https://github.com/gngc-5-team/MafiaAI']])}</article></div>${projectIndex(artworks.filter(a=>a.id==='cooking'))}${foot('community')}`
};
document.addEventListener('click',e=>{const project=e.target.closest('[data-project]');if(project)openProject(project.dataset.project);const zone=e.target.closest('[data-zone]');if(zone)openZone(zone.dataset.zone);if(e.target.closest('[data-overview]'))overview();});
$('#overview-button').onclick=overview;$('#fallback-button').onclick=overview;$('.skip-link').onclick=e=>{e.preventDefault();overview();};$('#close-dialog').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
const startExplore=()=>{exploring=true;mapOverview=false;$('#campus').classList.add('exploring');$('#intro').inert=true;world.focus({preventScroll:true});};$('#explore-button').onclick=startExplore;$('.brand').onclick=e=>{e.preventDefault();exploring=false;mapOverview=true;$('#campus').classList.remove('exploring');$('#intro').inert=false;};
let reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;$('#motion-button').setAttribute('aria-pressed',String(reduced));$('#motion-button').textContent=reduced?'Enable motion':'Reduce motion';$('#motion-button').onclick=()=>{reduced=!reduced;$('#motion-button').setAttribute('aria-pressed',String(reduced));$('#motion-button').textContent=reduced?'Enable motion':'Reduce motion';};
let renderer;
try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'});}catch(e){$('#fallback').hidden=false;$('#zone-labels').classList.add('hidden');$('#loading').classList.add('loaded');console.warn('3D unavailable',e);}
if(renderer)buildWorld();
function buildWorld(){
renderer.setPixelRatio(Math.min(devicePixelRatio,1.8));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.setClearColor(0xdcebdc);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;world.appendChild(renderer.domElement);
const scene=new THREE.Scene();scene.fog=new THREE.Fog(0xdcebdc,65,150);
const camera=new THREE.OrthographicCamera(-25,25,20,-20,.1,180);const aim=new THREE.Vector3();
scene.add(new THREE.HemisphereLight(0xfff8e6,0x6f907b,2.3));const sun=new THREE.DirectionalLight(0xffeed9,4);sun.position.set(-16,30,18);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-28,right:28,top:24,bottom:-25,near:1,far:90});sun.shadow.bias=-.001;sun.shadow.normalBias=.06;scene.add(sun);
const mats={};function mat(c,opts={}){const k=String(c)+JSON.stringify(opts);return mats[k]??(mats[k]=new THREE.MeshStandardMaterial({color:c,roughness:.78,...opts}));}
function box(w,h,d,c,x=0,y=0,z=0,parent=scene,opts={}){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(c,opts));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
function cyl(rt,rb,h,c,x=0,y=0,z=0,parent=scene,n=12){const m=new THREE.Mesh(new THREE.CylinderGeometry(rt,rb,h,n),mat(c));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
function sphere(r,c,x,y,z,parent=scene){const m=new THREE.Mesh(new THREE.IcosahedronGeometry(r,1),mat(c));m.position.set(x,y,z);m.castShadow=true;parent.add(m);return m;}
function textPlane(text,w,h,bg,fg,parent,x,y,z,fontSize=70){const canvas=document.createElement('canvas');canvas.width=1024;canvas.height=Math.round(1024*h/w);const ctx=canvas.getContext('2d');ctx.fillStyle=bg;ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle=fg;ctx.textAlign='center';ctx.textBaseline='middle';ctx.font=`700 ${fontSize}px sans-serif`;ctx.fillText(text,512,canvas.height/2);const t=new THREE.CanvasTexture(canvas);t.colorSpace=THREE.SRGBColorSpace;const mesh=new THREE.Mesh(new THREE.PlaneGeometry(w,h),new THREE.MeshStandardMaterial({map:t,roughness:.8}));mesh.position.set(x,y,z);parent.add(mesh);return mesh;}
// A playable miniature campus, built as actual lit 3D geometry.
box(250,.3,250,0xdcebdc,0,-2.1,0);box(35.8,1.35,26.2,0x779b7b,0,-.75,0);box(36,.28,26.5,0xb3cd99,0,.05,0);box(34.8,.08,25.3,0xa9c38a,0,.23,0);
// Campus paths, curb and central plaza.
box(28,.12,3.5,0xe7d8b7,0,.34,5.3);box(3.4,.12,17,0xe7d8b7,-3,.34,-1.6);box(24,.12,2.7,0xe7d8b7,1,.34,-.5);box(3,.12,10,0xe7d8b7,12,.34,3.2);box(6,.12,5,0xe7d8b7,0,.34,4.1);
for(let i=0;i<20;i++){box(.08,.025,3.4,0xd3c4a2,-13+i*1.4,.412,5.3);}for(let i=0;i<11;i++)box(3.3,.025,.07,0xd3c4a2,-3,.412,-9+i*1.4);
// Perimeter low fences and gateposts.
for(let x=-16;x<=16;x+=2){for(const z of[-11.6,11.6]){box(.16,.68,.16,0xf7edd4,x,.61,z);if(x<16)box(2,.11,.13,0xf7edd4,x+1,.85,z);}}
for(let z=-10;z<=10;z+=2){for(const x of[-16.9,16.9]){box(.16,.68,.16,0xf7edd4,x,.61,z);box(.13,.11,2,0xf7edd4,x,.85,z+1);}}
const clickable=[];function zoneGroup(id,x,z){const g=new THREE.Group();g.position.set(x,.35,z);g.userData.zone=id;scene.add(g);clickable.push(g);return g;}
// LEVEL0 clubhouse: coral roof, open terrace, noticeboard.
const club=zoneGroup('community',-8,-3);box(6,.28,5.3,0xf7e6c3,0,.1,0,club);box(5,2.7,3.8,0xf4e7c8,0,1.55,-.5,club);box(5.6,.24,4.4,0xd57054,0,3.05,-.5,club);
const roof=new THREE.Mesh(new THREE.CylinderGeometry(0,4.0,1.4,4),mat(0xd77052));roof.rotation.y=Math.PI/4;roof.scale.z=.8;roof.position.set(0,3.84,-.5);roof.castShadow=true;club.add(roof);
for(const x of[-1.55,1.55]){box(1.12,1.1,.08,0x4b7772,x,1.8,1.43,club);box(.07,1.2,.12,0xfdf1d2,x,1.8,1.49,club);box(1.2,.07,.12,0xfdf1d2,x,1.8,1.49,club);}box(.9,1.7,.12,0x416a61,0,1.18,1.48,club);box(1.4,.15,.7,0xe7bfa2,0,.25,1.85,club);
textPlane('LEVEL 0',3.1,.5,'#274f42','#fff0ce',club,0,2.75,1.77,115);box(5.1,.11,1.3,0xf4ac78,0,2.6,2.0,club);for(const x of[-2.4,2.4])box(.1,2.3,.1,0xf0e5c9,x,1.35,2.48,club);
// Deck benches and a small outside gathering table.
const bench=(x,z,rot=0)=>{const g=new THREE.Group();g.position.set(x,.4,z);g.rotation.y=rot;scene.add(g);box(1.8,.15,.6,0xcb945c,0,.45,0,g);box(1.8,.42,.12,0xcb945c,0,.78,-.3,g);for(const xx of[-.65,.65])box(.1,.45,.48,0x355d4d,xx,.2,0,g);};bench(-11.7,.65);bench(-7.7,1.2);
// Workshop: stacked ivory volumes, green glass, rooftop connector sculpture.
const lab=zoneGroup('lab',2,-7);box(6.4,.3,5.2,0xc3ceac,0,.1,0,lab);box(5.3,3.2,4,0xf5f0d9,0,1.8,0,lab);box(5.65,.22,4.3,0xfdf8e5,0,3.52,0,lab);box(3.4,1.65,.12,0x567b68,-.5,1.9,2.04,lab,{metalness:.25,roughness:.26});for(const x of[-2.18,-1.08,.02,1.12])box(.08,1.85,.2,0xe7e7cb,x,1.9,2.13,lab);box(.8,2.15,.15,0x294f44,1.96,1.47,2.1,lab);textPlane('CLAUDE × UNITY',4.5,.5,'#e1eea0','#284837',lab,0,3.04,2.14,86);
const connector=new THREE.Group();connector.position.set(0,4.1,0);lab.add(connector);const ring=new THREE.Mesh(new THREE.TorusGeometry(.76,.12,6,20),mat(0xbadd55));ring.rotation.y=.25;connector.add(ring);box(.3,.3,.3,0xecad65,0,0,0,connector);for(let i=0;i<4;i++){const a=i*Math.PI/2;box(.24,.24,.24,0x264d42,Math.cos(a)*1.1,Math.sin(a)*1.1,0,connector);}
// Arcade pavilion with lilac sawtooth canopy and three real cabinet objects.
const arcade=zoneGroup('arcade',10,3);box(6,.3,4.7,0xbfb4d0,0,.1,0,arcade);box(5.2,2.85,3.2,0x6b7199,0,1.65,-.3,arcade);box(5.65,.4,3.7,0xb9a6d0,0,3.12,-.2,arcade);box(5.9,.23,1.2,0xd3bedf,0,2.82,1.8,arcade);textPlane('PLAY / REPEAT',4.6,.58,'#d6c5e8','#3a4059',arcade,0,3.16,1.69,96);
for(const [i,c] of[0xe6a986,0xd8df82,0xbca9df].entries()){const x=-1.65+i*1.65;box(1.2,1.8,.75,c,x,1.3,1.0,arcade);box(.91,.76,.1,0x263b4e,x,1.65,1.41,arcade);textPlane(['GO!','AI','↑ ↑'][i],.72,.45,'#263b4e',['#edc99c','#d4ef8f','#d9bef3'][i],arcade,x,1.66,1.472,160);box(1.18,.14,.5,c,x,1.09,1.55,arcade);cyl(.045,.045,.14,0x273e46,x-.26,1.24,1.58,arcade);sphere(.08,0xc9544d,x-.26,1.33,1.58,arcade);cyl(.07,.07,.035,0xf9f0d7,x+.22,1.18,1.57,arcade);}
// Playground details.
const trees=[];function tree(x,z,scale=1){const g=new THREE.Group();g.position.set(x,.4,z);g.scale.setScalar(scale);scene.add(g);cyl(.12,.2,1.6,0x927754,0,.8,0,g,7);sphere(.98,0x648e54,0,2.05,0,g);sphere(.75,0x8ead64,-.36,2.5,.08,g);trees.push(g);}
[[-14,-8,1.3],[-13,-4,1],[-14.3,4,1.3],[-12,8.4,1.15],[-7,9,1],[-.5,9,1.05],[5.4,9.3,1.25],[13.8,-8.9,1.4],[14,-4.8,1.1],[7.1,-9.8,.8],[-4.2,-10.2,1],[13,8,1.15],[-13,-10.8,.65]].forEach(a=>tree(...a));
for(let i=0;i<17;i++){const x=-14+i*1.7;box(.55,.2,.55,[0xd5dfa3,0xf2cd9c,0xbac68a][i%3],x,.52,10);}
// Central campus monument and miniature flag.
cyl(1.15,1.3,.26,0xe9e4c9,2.8,.54,1.6);box(.86,.85,.86,0x456e51,2.8,1.09,1.6);const monument=box(.8,.8,.8,0xd0ec68,2.8,2.03,1.6);monument.rotation.set(.2,.3,.2);cyl(.045,.045,3.3,0x456353,-4.9,2.05,1);const flag=box(.85,.5,.055,0xd98363,-4.45,3.35,1);textPlane('BUILD',1.5,.37,'#f2edcf','#456548',scene,2.8,.95,2.05,100);
// Tiny parking space and decorative plants.
box(3,.035,1.8,0x96af7c,-.4,.42,8.4);for(const x of[-1.8,1])box(.08,.04,1.8,0xeae5c8,x,.45,8.4);bench(6,-1,Math.PI/2);
function lamp(x,z){cyl(.045,.06,2.3,0x3a6557,x,1.55,z);box(.4,.08,.4,0x365b4e,x,2.76,z);box(.28,.3,.28,0xf6edb5,x,2.56,z,scene,{emissive:0xe5d28e,emissiveIntensity:.35});}lamp(-3.9,6.9);lamp(6.2,6.9);lamp(-3.9,-.8);lamp(6.4,-2);
// Enlarge the playable campus to twice its original ground area.
const environment=new THREE.Group();for(const child of [...scene.children])if(child.isMesh||child.isGroup)environment.add(child);environment.scale.setScalar(MAP_SCALE);scene.add(environment);
// A walking visitor with articulated arms and legs.
const player=new THREE.Group();scene.add(player);player.position.set(-2*MAP_SCALE,.51*MAP_SCALE,5.4*MAP_SCALE);
box(.62,.66,.42,0x3f735b,0,1.26,0,player);box(.52,.15,.39,0x345d4b,0,.91,0,player);
sphere(.29,0xe5b68a,0,1.91,.025,player);box(.51,.18,.48,0x273f36,0,2.09,-.025,player);box(.52,.08,.5,0xd4db8c,0,2.19,0,player);box(.51,.06,.24,0xd4db8c,0,2.17,.31,player);
for(const x of[-.105,.105])box(.045,.055,.035,0x263e35,x,1.94,.293,player);
box(.46,.51,.2,0xd5845d,0,1.24,-.31,player);box(.29,.21,.07,0xb56a49,0,1.12,-.43,player);
const arms=[],legs=[];for(const x of[-1,1]){const arm=new THREE.Group();arm.position.set(x*.4,1.51,0);player.add(arm);box(.2,.45,.23,0x477b5f,0,-.2,0,arm);sphere(.12,0xe5b68a,0,-.48,0,arm);arms.push(arm);const leg=new THREE.Group();leg.position.set(x*.18,.91,0);player.add(leg);box(.24,.57,.27,0xd9cdb2,0,-.28,0,leg);box(.28,.16,.43,0x304940,0,-.6,.065,leg);legs.push(leg);}
const you=textPlane('YOU',.9,.33,'#254739','#f7edc9',player,0,2.65,0,140);you.material.side=THREE.DoubleSide;
let gait=0;const viewAim=new THREE.Vector3(-4,0,0);
$('#map-view').onclick=()=>{if(!exploring){startExplore();mapOverview=false;}else mapOverview=!mapOverview;$('#map-view').textContent=mapOverview?'Follow me':'Full map';};
// Physical key positions stay stable across English and Korean input methods.
const keys=new Set();const dirKeys={KeyW:'up',ArrowUp:'up',KeyS:'down',ArrowDown:'down',KeyA:'left',ArrowLeft:'left',KeyD:'right',ArrowRight:'right'};
window.addEventListener('keydown',e=>{if(dialog.open||rooms.isOpen||e.altKey||e.ctrlKey||e.metaKey||e.target.isContentEditable||['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName))return;const code=e.code;if(dirKeys[code]&&(e.target===document.body||world.contains(e.target))){e.preventDefault();if(!keys.has(dirKeys[code]))nudge(dirKeys[code]);keys.add(dirKeys[code]);if(!exploring)startExplore();}if(code==='KeyE'&&nearZone&&!e.repeat){e.preventDefault();keys.clear();openZone(nearZone);}if(code==='Escape'){keys.clear();}});window.addEventListener('keyup',e=>keys.delete(dirKeys[e.code]));window.addEventListener('blur',()=>keys.clear());dialog.addEventListener('close',()=>{keys.clear();world.focus({preventScroll:true});});
for(const btn of document.querySelectorAll('[data-dir]')){btn.addEventListener('pointerdown',e=>{e.preventDefault();btn.setPointerCapture(e.pointerId);nudge(btn.dataset.dir);keys.add(btn.dataset.dir);if(!exploring)startExplore();});for(const event of['pointerup','pointercancel','lostpointercapture'])btn.addEventListener(event,()=>keys.delete(btn.dataset.dir));}
$('#reset-button').onclick=()=>{player.position.set(-2*MAP_SCALE,.51*MAP_SCALE,5.4*MAP_SCALE);player.rotation.y=0;keys.clear();};
const ray=new THREE.Raycaster(),mouse=new THREE.Vector2();let pointerStart=null;
world.addEventListener('pointerdown',e=>pointerStart={x:e.clientX,y:e.clientY});world.addEventListener('pointerup',e=>{if(!pointerStart||Math.hypot(e.clientX-pointerStart.x,e.clientY-pointerStart.y)>8)return;const r=world.getBoundingClientRect();mouse.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(mouse,camera);const hit=ray.intersectObjects(clickable,true)[0];if(hit){let g=hit.object;while(g&&!g.userData.zone)g=g.parent;if(g)openZone(g.userData.zone);}});
const anchors=Object.entries(zoneInfo).map(([id,z])=>({el:document.querySelector(`.world-label[data-zone="${id}"]`),p:new THREE.Vector3(z.x,z.anchorY,z.z)}));
function resize(){const w=world.clientWidth,h=world.clientHeight;renderer.setSize(w,h);const aspect=w/h;const mobile=w<701;const scale=(mobile?23/aspect:Math.max(19,24/aspect))*MAP_SCALE;camera.left=-scale*aspect;camera.right=scale*aspect;camera.top=scale;camera.bottom=-scale;camera.updateProjectionMatrix();aim.set(mobile?0:-4,mobile?2:0,mobile?0:0);camera.position.copy(aim).add(new THREE.Vector3(30,36,38));camera.lookAt(aim);if(mobile)camera.setViewOffset(w,h,0,-h*.08,w,h);else camera.clearViewOffset();}
window.addEventListener('resize',resize);resize();
let nearZone=null,prevTime=performance.now(),elapsed=0;const tmp=new THREE.Vector3();
const obstacles=[{x:-8,z:-3,w:5.9,d:5.6},{x:2,z:-7,w:6.1,d:5},{x:10,z:3,w:6,d:4.7},{x:2.8,z:1.6,w:2.9,d:2.9}].map(o=>({x:o.x*MAP_SCALE,z:o.z*MAP_SCALE,w:o.w*MAP_SCALE,d:o.d*MAP_SCALE}));
function blocked(x,z){return Math.abs(x)>16.2*MAP_SCALE||Math.abs(z)>11*MAP_SCALE||obstacles.some(b=>Math.abs(x-b.x)<b.w/2+.35&&Math.abs(z-b.z)<b.d/2+.4);}
function nudge(dir){const [dx,dz]={up:[-.707,-.707],down:[.707,.707],left:[-.707,.707],right:[.707,-.707]}[dir];const step=.22;const nx=player.position.x+dx*step,nz=player.position.z+dz*step;if(!blocked(nx,player.position.z))player.position.x=nx;if(!blocked(player.position.x,nz))player.position.z=nz;player.rotation.y=Math.atan2(dx,dz);}
$('#nearby').onclick=()=>{if(nearZone)openZone(nearZone);};
function tick(now){requestAnimationFrame(tick);const dt=Math.min((now-prevTime)/1000,.04);prevTime=now;if(document.hidden||rooms.isOpen)return;elapsed+=dt;let dx=0,dz=0;if(!dialog.open){if(keys.has('up')){dx-=.707;dz-=.707;}if(keys.has('down')){dx+=.707;dz+=.707;}if(keys.has('left')){dx-=.707;dz+=.707;}if(keys.has('right')){dx+=.707;dz-=.707;}}
const moving=dx||dz;if(moving){const length=Math.hypot(dx,dz);dx/=length;dz/=length;const speed=4.5;const nx=player.position.x+dx*dt*speed,nz=player.position.z+dz*dt*speed;if(!blocked(nx,player.position.z))player.position.x=nx;if(!blocked(player.position.x,nz))player.position.z=nz;const target=Math.atan2(dx,dz);let delta=target-player.rotation.y;delta=Math.atan2(Math.sin(delta),Math.cos(delta));player.rotation.y+=delta*Math.min(dt*10,1);gait+=dt*10;player.position.y=.51*MAP_SCALE+(reduced?0:Math.abs(Math.sin(gait))*.065);}else player.position.y=.51*MAP_SCALE;for(let i=0;i<2;i++){const angle=moving&&!reduced?Math.sin(gait+i*Math.PI)*.55:0;arms[i].rotation.x=THREE.MathUtils.lerp(arms[i].rotation.x,-angle,.25);legs[i].rotation.x=THREE.MathUtils.lerp(legs[i].rotation.x,angle,.25);}
const targetAim=mapOverview?new THREE.Vector3(world.clientWidth<701?0:-4,world.clientWidth<701?2:0,0):new THREE.Vector3(player.position.x,1,player.position.z);viewAim.lerp(targetAim,reduced?1:Math.min(dt*4,1));camera.position.copy(viewAim).add(new THREE.Vector3(30,36,38));camera.lookAt(viewAim);const targetZoom=mapOverview?1:(world.clientWidth<701?2.7:1.65);camera.zoom=THREE.MathUtils.lerp(camera.zoom,targetZoom,reduced?1:Math.min(dt*4,1));camera.updateProjectionMatrix();
you.quaternion.copy(player.quaternion).invert().multiply(camera.quaternion);if(!reduced&&!dialog.open){connector.rotation.y=Math.sin(elapsed*.5)*.25;monument.rotation.y=elapsed*.3;flag.rotation.y=Math.sin(elapsed*1.3)*.07;}
for(const a of anchors){tmp.copy(a.p).project(camera);const isMobile=world.clientWidth<701;const id=a.el.dataset.zone;const offset=isMobile?({community:[-36,-14],lab:[31,-26],arcade:[38,5]}[id]):[0,0];a.el.style.left=`${(tmp.x*.5+.5)*world.clientWidth+offset[0]}px`;a.el.style.top=`${(-tmp.y*.5+.5)*world.clientHeight+offset[1]}px`;const lx=parseFloat(a.el.style.left),ly=parseFloat(a.el.style.top);a.el.style.visibility=(lx<a.el.offsetWidth/2+5||lx>world.clientWidth-a.el.offsetWidth/2-5||ly<105||ly>world.clientHeight-140)?'hidden':'visible';}
nearZone=null;let best=5.1*MAP_SCALE;for(const[id,z]of Object.entries(zoneInfo)){const distance=Math.hypot(player.position.x-z.x,player.position.z-(z.z+2.5*MAP_SCALE));if(distance<best){nearZone=id;best=distance;}}$('#nearby').classList.toggle('hidden',!nearZone||!exploring||dialog.open);if(nearZone)$('#nearby span').textContent=`Enter ${zoneInfo[nearZone].name}`;renderer.render(scene,camera);}
requestAnimationFrame(tick);requestAnimationFrame(()=>{ $('#loading').classList.add('loaded'); $('#loading').setAttribute('aria-hidden','true'); });
}
