// Korean copy for text owned by index.html, app.js and campus-encounters.js.
// Keys retain the rendered English source. Whitespace normalization belongs to
// the central locale layer. Both <br>-separated text nodes and joined copy are
// included where useful; imported project data belongs to its own dictionary.
export const koCampus = {
  // Document metadata and the campus entrance.
  "Explore Yumin Kang’s builder campus: games made with Claude, a student community, startup projects, personal tools and industry practice.": "강유민의 빌더 캠퍼스를 둘러보세요. Claude와 만든 게임부터 학생 커뮤니티, 창업 프로젝트, 개인 도구, 현장 실습까지 담았습니다.",
  "YUMIN CAMPUS — Yumin Kang": "YUMIN CAMPUS — 강유민",
  "Yumin Kang · Builder Campus": "강유민 · 빌더 캠퍼스",
  "Games, useful tools and people who build. Explore my interactive portfolio campus.": "게임과 쓸모 있는 도구, 그리고 함께 만드는 사람들. 직접 걸으며 살펴보는 포트폴리오 캠퍼스입니다.",
  "View projects": "프로젝트 보기",
  "3D campus. Use arrow keys or W A S D to walk, and E to enter a nearby space. Press F to say hello to a nearby person. You can also click a building or a person.": "3D 캠퍼스입니다. 방향키 또는 W A S D로 걷고, E를 눌러 가까운 공간에 들어가세요. F를 누르면 가까운 사람에게 인사할 수 있습니다. 건물이나 사람을 클릭해도 됩니다.",
  "Arriving on campus…": "캠퍼스에 도착하는 중…",
  "Back to the campus entrance": "캠퍼스 입구로 돌아가기",
  "BUILDER CAMPUS": "빌더 캠퍼스",
  "Main navigation": "주 메뉴",
  "YUMIN KANG · PORTFOLIO 2026": "강유민 · 포트폴리오 2026",
  "Build.": "만들어요.",
  "Together.": "함께.",
  "Build. Together.": "만들어요. 함께.",
  "I build games and useful tools.": "게임과 쓸모 있는 도구를 만듭니다.",
  "And bring people together to build.": "함께 만들 사람들을 연결합니다.",
  "I build games and useful tools. And bring people together to build.": "게임과 쓸모 있는 도구를 만들고, 함께 만들 사람들을 연결합니다.",
  "Explore the campus": "캠퍼스 둘러보기",
  "Four spaces. One story of making.": "네 공간에 담은, 만들어 온 이야기.",
  "Campus spaces": "캠퍼스의 공간들",
  "LEVEL0 CLUBHOUSE": "LEVEL0 동아리방",
  "LEVEL0 Clubhouse": "LEVEL0 동아리방",
  "Open a locker. Meet the community.": "사물함을 열고, 함께한 사람들을 만나보세요.",
  "CLAUDE × UNITY": "CLAUDE × UNITY",
  "Step inside the making gallery.": "작품이 만들어진 과정을 만나보세요.",
  "GAME ARCADE": "게임 아케이드",
  "Game Arcade": "게임 아케이드",
  "INSERT COIN · Find your next game.": "동전을 넣고 · 다음 게임을 찾아보세요.",
  "BUILDER’S STUDIO": "빌더의 작업실",
  "Builder’s Studio": "빌더의 작업실",
  "Project tapes. Favorite games. Come in.": "프로젝트 테이프와 좋아하는 게임들. 들어오세요.",
  "Go directly to a space": "공간으로 바로 이동",
  "CAMPUS DIRECTORY": "캠퍼스 안내",
  "COMMUNITY": "커뮤니티",
  "AI WORKSHOP": "AI 워크숍",
  "PLAYGROUND": "플레이그라운드",
  "DAEGU, KR": "대한민국, 대구",
  "From idea to play.": "아이디어에서 플레이까지.",
  "Move": "이동",
  "Enter": "입장",
  "Return the character to the starting point": "캐릭터를 시작 위치로 돌려보내기",
  "Reset": "처음 위치로",
  "Full map": "전체 지도",
  "Follow me": "내 위치 따라가기",
  "Reduce motion": "움직임 줄이기",
  "Enable motion": "움직임 켜기",
  "Walking controls": "걷기 조작",
  "Walk forward": "앞으로 걷기",
  "Walk left": "왼쪽으로 걷기",
  "Walk backward": "뒤로 걷기",
  "Walk right": "오른쪽으로 걷기",
  "Explore the projects directly.": "프로젝트를 바로 살펴보세요.",
  "3D is unavailable in this browser. You can still explore every project in the overview.": "이 브라우저에서는 3D 화면을 사용할 수 없습니다. 프로젝트 모아보기에서 모든 작품을 살펴볼 수 있습니다.",
  "Yumin Kang · Project archive ↗": "강유민 · 프로젝트 아카이브 ↗",
  "Yumin Kang · Project archive": "강유민 · 프로젝트 아카이브",
  "Close project overview": "프로젝트 모아보기 닫기",

  // Overview and the non-WebGL project panels.
  "Selected projects": "주요 프로젝트",
  "Choose a work": "작품을 골라보세요",
  "projects · Choose a work": "개 프로젝트 · 작품을 골라보세요",
  "SELECTED WORK /": "주요 작품 /",
  "YUMIN'S BUILDER CAMPUS": "유민의 빌더 캠퍼스",
  "Games, useful tools.": "게임과 쓸모 있는 도구.",
  "And people who build.": "그리고 함께 만드는 사람들.",
  "Games, useful tools. And people who build.": "게임과 쓸모 있는 도구. 그리고 함께 만드는 사람들.",
  "Yumin Kang · Computer Software, Daegu University": "강유민 · 대구대학교 컴퓨터소프트웨어",
  "Developer / Founder of LEVEL0": "개발자 / LEVEL0 설립자",
  "Yumin Kang · Computer Software, Daegu University Developer / Founder of LEVEL0": "강유민 · 대구대학교 컴퓨터소프트웨어 · 개발자 / LEVEL0 설립자",
  "From finding teammates to six teams shipping their first jam games.": "팀원을 찾는 순간부터, 여섯 팀이 첫 게임잼 작품을 완성하기까지.",
  "Using Claude Code and Unity MCP to inspect, build and debug in the editor.": "Claude Code와 Unity MCP로 에디터 안에서 확인하고, 만들고, 디버깅합니다.",
  "Insert a coin to discover playable games and our first game jam.": "동전을 넣고, 직접 즐길 수 있는 게임과 첫 게임잼을 만나보세요.",
  "A lived-in home. Browse project tapes and discover the work behind each case.": "생활의 흔적이 담긴 집입니다. 프로젝트 테이프를 골라, 각 작업에 담긴 과정을 살펴보세요.",
  "Resume PDF ↓": "이력서 PDF ↓",
  "Resume PDF": "이력서 PDF",
  "Project archive ↗": "프로젝트 아카이브 ↗",
  "Project archive": "프로젝트 아카이브",
  "← All projects": "← 모든 프로젝트",
  "All projects": "모든 프로젝트",
  "Next space →": "다음 공간 →",
  "Next space": "다음 공간",
  "04 / BUILDER’S STUDIO": "04 / 빌더의 작업실",
  "Ideas into everyday tools.": "아이디어를 일상의 도구로.",
  "Startup experiments, independent tools and industry practice. Pick a project tape from the archive.": "창업 실험과 직접 만든 도구, 현장 실습까지. 아카이브에서 프로젝트 테이프를 골라보세요.",
  "Startup program record": "창업 지원 프로그램 기록",
  "Explore Modoo Startup →": "모두의 창업 살펴보기 →",
  "Explore Modoo Startup": "모두의 창업 살펴보기",
  "01 / COMMUNITY · LEVEL0 CLUBHOUSE": "01 / 커뮤니티 · LEVEL0 동아리방",
  "A place to find": "함께 만들 사람을",
  "your fellow builders.": "만나는 곳.",
  "A place to find your fellow builders.": "함께 만들 사람을 만나는 곳.",
  "I founded LEVEL0, a university game development club, and became its first president. I connected designers, artists and programmers, helping first-time makers take their projects through to completion.": "대학교 게임 개발 동아리 LEVEL0를 설립하고 초대 회장을 맡았습니다. 기획자, 아티스트, 프로그래머를 연결하고, 처음 게임을 만드는 사람들도 프로젝트를 끝까지 완성할 수 있도록 도왔습니다.",
  "Founding members": "창립 멤버",
  "Teams in our first jam": "첫 게임잼 참가 팀",
  "Browser games submitted": "제출된 브라우저 게임",
  "From recruitment to the first playtest": "동아리원 모집부터 첫 플레이테스트까지",
  "I led recruitment, assigned roles and formed teams, using Discord, Notion and GitHub for collaboration. For our first game jam, I coordinated the schedule, exhibition, external judging and student voting. I also joined one of the development teams.": "동아리원 모집과 역할 배정, 팀 구성을 이끌고 Discord, Notion, GitHub로 협업했습니다. 첫 게임잼에서는 일정과 전시, 외부 심사, 학생 투표를 조율했으며, 개발팀의 일원으로도 참여했습니다.",
  "01 · Connect": "01 · 연결하기",
  "Bring designers, artists and programmers together into teams.": "기획자, 아티스트, 프로그래머를 연결해 팀을 만듭니다.",
  "02 · Finish": "02 · 완성하기",
  "All six teams submitted games that anyone could play in a browser.": "여섯 팀 모두 누구나 브라우저에서 즐길 수 있는 게임을 제출했습니다.",
  "03 · Grow": "03 · 성장하기",
  "Help co-organize a regional game jam connecting eight universities.": "8개 대학을 잇는 지역 게임잼의 공동 운영에 참여합니다.",
  "Play the jam entries": "게임잼 출품작 플레이",
  "Club records": "동아리 활동 기록",
  "02 / AI WORKSHOP": "02 / AI 워크숍",
  "Prototype in development": "개발 중인 프로토타입",
  "Building with Claude.": "Claude와 함께 만들고,",
  "Debugging in the game.": "게임 안에서 디버깅합니다.",
  "Building with Claude. Debugging in the game.": "Claude와 함께 만들고, 게임 안에서 디버깅합니다.",
  "For Job Battle, I defined the rules and art direction, then connected Claude Code to Unity MCP. I used the editor and live play-mode state to check what the code was actually doing.": "Job Battle의 게임 규칙과 아트 방향을 정하고, Claude Code를 Unity MCP에 연결했습니다. 에디터와 실행 중인 플레이 모드 상태를 살펴보며 코드가 실제로 어떻게 동작하는지 확인했습니다.",
  "The code looked right. The character stayed still.": "코드는 맞아 보였지만, 캐릭터는 움직이지 않았습니다.",
  "Idle and Attack animation errors kept returning after fixes. Inspecting the player created at runtime revealed that its Animator had no controller assigned.": "수정 후에도 Idle과 Attack 애니메이션 오류가 반복됐습니다. 실행 중 생성된 플레이어를 살펴보니 Animator에 컨트롤러가 지정되어 있지 않았습니다.",
  "Inspect the live state": "실행 중인 상태 확인",
  "Use Unity MCP to inspect the scene, console and runtime player’s Animator.": "Unity MCP로 씬, 콘솔, 실행 중 생성된 플레이어의 Animator를 확인합니다.",
  "Fix the root cause": "근본 원인 수정",
  "Change setup code to reuse the existing controller asset instead of deleting and recreating it.": "컨트롤러를 삭제하고 다시 만들던 설정 코드를 고쳐, 기존 컨트롤러 에셋을 재사용하도록 합니다.",
  "Check in play mode": "플레이 모드에서 검증",
  "Confirm the controller assignment, Idle playback and entry into Attack.": "컨트롤러 지정, Idle 재생, Attack 진입을 확인합니다.",
  "My decisions. Built and tested with Claude.": "방향은 제가 정하고, Claude와 함께 만들고 검증했습니다.",
  "I defined the four-player territory-control rules, practice bots, art direction and priorities. With Claude, I iterated on code, editor integration and debugging, then played the results and refined them.": "4인 영역 점령 규칙, 연습용 봇, 아트 방향과 우선순위를 정했습니다. Claude와 코드 작성, 에디터 연동, 디버깅을 반복하고, 결과물을 직접 플레이하며 다듬었습니다.",
  "Job Battle code": "Job Battle 코드",
  "Development notes": "개발 기록",
  "03 / PLAYGROUND": "03 / 플레이그라운드",
  "Less explaining.": "설명은 짧게.",
  "More playing.": "플레이는 더 많이.",
  "Less explaining. More playing.": "설명은 짧게. 플레이는 더 많이.",
  "From browser races to deduction with local AI.": "브라우저 레이싱부터 로컬 AI와의 추리 게임까지.",
  "Ideas made into things you can play.": "아이디어를 직접 즐길 수 있는 게임으로 만들었습니다.",
  "From browser races to deduction with local AI. Ideas made into things you can play.": "브라우저 레이싱부터 로컬 AI와의 추리 게임까지. 아이디어를 직접 즐길 수 있는 게임으로 만들었습니다.",
  "RACE / WEB GAME": "레이싱 / 웹 게임",
  "A browser racing game with transformations, weather and cinematic camera work. Building with Claude, I refined the camera to keep the chasing horses in view.": "변신과 날씨, 영화 같은 카메라 연출을 담은 브라우저 레이싱 게임입니다. Claude와 함께 개발하며, 추격하는 말들이 화면에 계속 보이도록 카메라를 다듬었습니다.",
  "Solo project": "개인 프로젝트",
  "Play now": "지금 플레이",
  "View code": "코드 보기",
  "DEDUCTION / LOCAL AI": "추리 / 로컬 AI",
  "A deduction game prototype for one human and five local AI players. I developed the rules, prompts, UI and Ollama integration.": "사람 한 명과 로컬 AI 다섯 명이 함께하는 추리 게임 프로토타입입니다. 게임 규칙, 프롬프트, UI, Ollama 연동을 개발했습니다.",
  "Team project": "팀 프로젝트",
  "Development: Claude Code + Unity MCP": "개발: Claude Code + Unity MCP",
  "In-game AI: Ollama + Gemma": "게임 내 AI: Ollama + Gemma",
  "Development: Claude Code + Unity MCP In-game AI: Ollama + Gemma": "개발: Claude Code + Unity MCP · 게임 내 AI: Ollama + Gemma",
  "Making the game": "게임 제작기",

  // Canvas signs. Brand and technology labels intentionally retain their names.
  "LEVEL 0": "LEVEL 0",
  "PLAY / REPEAT": "플레이 / 한 판 더",
  "GO!": "출발!",
  "AI": "AI",
  "VHS": "VHS",
  "BUILD": "만들기",
  "YOU": "나",

  // Nearby-building prompts are generated from zoneInfo.name.
  "Enter LEVEL0 Clubhouse": "LEVEL0 동아리방 들어가기",
  "Enter CLAUDE × UNITY": "CLAUDE × UNITY 들어가기",
  "Enter Game Arcade": "게임 아케이드 들어가기",
  "Enter Builder’s Studio": "빌더의 작업실 들어가기",

  // Campus encounters: a warm postman, playful club members, lively announcer.
  "The campus postman": "캠퍼스 우체부 할아버지",
  "Special delivery": "특별한 배달",
  "Listen for a bicycle on the lane around the studio.": "작업실 주변 길에서 자전거 소리에 귀를 기울여 보세요.",
  "Ring ring! A delivery for the next person with a strange idea.": "따르릉! 별난 아이디어를 떠올릴 다음 사람에게 온 편지라네.",
  "No bills today. Just a reminder to finish that prototype.": "오늘은 고지서가 아니라네. 그 프로토타입, 끝까지 만들어 보라는 작은 당부지.",
  "One postcard, three bugs, and a very promising first draft.": "엽서 한 장, 버그 세 개, 그리고 제법 기대되는 첫 초안이라네.",
  "The LEVEL0 crew": "LEVEL0 친구들",
  "Caught playtesting": "플레이테스트하다 들켰다!",
  "Someone might be hiding behind the clubhouse…": "동아리방 뒤에 누군가 숨어 있을지도 몰라요…",
  "Psst… new teammate? We were definitely playtesting. Definitely.": "쉿… 새 팀원이야? 우린 분명 플레이테스트 중이었어. 진짜로.",
  "Come inside. There’s room for one more builder.": "들어와. 함께 만들 사람이 한 명 더 들어올 자리는 있어.",
  "We said one more round. That was three rounds ago.": "한 판만 더 하자고 했는데. 그 말을 한 게 세 판 전이네.",
  "The neighborhood announcer": "동네 방송 아주머니",
  "A very important announcement": "아주 중요한 안내 방송",
  "Someone near the clubhouse has a lot to say.": "동아리방 근처에 할 말이 아주 많은 분이 있어요.",
  "Attention, attention! Ask someone to play your game.": "아, 아! 주목해 주세요! 여러분의 게임, 다른 사람에게도 한번 해 보라고 하세요!",
  "The arcade is open. Your excuses are closed.": "아케이드는 문 열었어요! 핑계는 이제 문 닫으세요!",
  "A first prototype doesn’t have to be perfect.": "첫 프로토타입부터 완벽할 필요는 없어요!",
  "Little moments": "작은 만남들",
  "Dismiss the conversation": "대화 닫기",
  "♪ Sound on": "♪ 소리 켜짐",
  "♪ Sound off": "♪ 소리 꺼짐",
  "Mute campus sounds": "캠퍼스 소리 끄기",
  "Enable campus sounds": "캠퍼스 소리 켜기",
  "NOTES FROM A WALK": "산책하며 남긴 기록",
  "Close little moments": "작은 만남들 닫기",
  "People make": "사람이 모여",
  "a campus.": "캠퍼스가 됩니다.",
  "People make a campus.": "사람이 모여 캠퍼스가 됩니다.",
  "Small encounters, somewhere between projects.": "프로젝트 사이사이에서 만나는 작은 인연들.",
  "Still out there": "아직 만나지 못했어요",
  "An unwritten page": "아직 쓰지 않은 한 페이지",
  "Back to the walk": "다시 산책하기",
  "New moment": "새로운 만남",
  "· New moment": "· 새로운 만남",
  "Postman": "우체부 할아버지",
  "LEVEL0 crew": "LEVEL0 친구들",
  "Announcer": "방송 아주머니",
  "Say hello": "인사하기",
  "Say hello · Postman": "우체부 할아버지에게 인사하기",
  "Say hello · LEVEL0 crew": "LEVEL0 친구들에게 인사하기",
  "Say hello · Announcer": "방송 아주머니에게 인사하기",
  "The campus postman · New moment": "캠퍼스 우체부 할아버지 · 새로운 만남",
  "The LEVEL0 crew · New moment": "LEVEL0 친구들 · 새로운 만남",
  "The neighborhood announcer · New moment": "동네 방송 아주머니 · 새로운 만남",
  "“Ring ring! A delivery for the next person with a strange idea.”": "“따르릉! 별난 아이디어를 떠올릴 다음 사람에게 온 편지라네.”",
  "“Psst… new teammate? We were definitely playtesting. Definitely.”": "“쉿… 새 팀원이야? 우린 분명 플레이테스트 중이었어. 진짜로.”",
  "“Attention, attention! Ask someone to play your game.”": "“아, 아! 주목해 주세요! 여러분의 게임, 다른 사람에게도 한번 해 보라고 하세요!”",

  // Dynamic counts: the locale layer should match arbitrary project counts and
  // SELECTED WORK / {no}. These literal values cover every current render.
  "1 projects · Choose a work": "프로젝트 1개 · 작품을 골라보세요",
  "4 projects · Choose a work": "프로젝트 4개 · 작품을 골라보세요",
  "5 projects · Choose a work": "프로젝트 5개 · 작품을 골라보세요",
  "6 projects · Choose a work": "프로젝트 6개 · 작품을 골라보세요",
  "10 projects · Choose a work": "프로젝트 10개 · 작품을 골라보세요",
  "SELECTED WORK / 01": "주요 작품 / 01",
  "SELECTED WORK / 02": "주요 작품 / 02",
  "SELECTED WORK / 03": "주요 작품 / 03",
  "SELECTED WORK / 04": "주요 작품 / 04",
  "SELECTED WORK / 05": "주요 작품 / 05",
  "SELECTED WORK / 06": "주요 작품 / 06",
  "SELECTED WORK / 07": "주요 작품 / 07",
  "SELECTED WORK / 08": "주요 작품 / 08",
  "SELECTED WORK / 09": "주요 작품 / 09",
  "SELECTED WORK / 10": "주요 작품 / 10",
  "SELECTED WORK / 2026": "주요 작품 / 2026",
  "0 of 3 little moments found": "작은 만남 3개 중 0개 발견",
  "1 of 3 little moments found": "작은 만남 3개 중 1개 발견",
  "2 of 3 little moments found": "작은 만남 3개 중 2개 발견",
  "3 of 3 little moments found": "작은 만남 3개 중 3개 발견"
};
