// Korean copy for room-data.js, rooms.js and art-media.js.
// Keys preserve the English source text. IDs, URLs and media paths are excluded.
export const koRoom = {
  // LEVEL0 memories, photo captions and alternative text.
  "The first page of LEVEL0": "LEVEL0의 첫 페이지",
  "AUG 2025 · FOUNDING THE CLUB": "2025년 8월 · 동아리 창설",
  "The beginning": "시작",
  "I brought together people at Daegu University who wanted to make games. As the founding president, I led recruitment, role allocation and team formation. Around 30 members joined us at the start.": "대구대학교에서 게임을 만들고 싶은 사람들을 모았습니다. 초대 회장으로서 모집과 역할 배분, 팀 구성을 이끌었고, 처음에는 약 30명의 회원이 함께했습니다.",
  "Read the founding story": "동아리 창설 이야기 보기",
  "BEGIN": "시작",
  "Our first jam. Six finished games.": "첫 게임잼, 완성된 게임 여섯 편.",
  "MAY 2026 · LEVEL0 FIRST GAME JAM": "2026년 5월 · LEVEL0 첫 게임잼",
  "Our first game jam": "우리의 첫 게임잼",
  "I planned and ran our first game jam. All six teams submitted browser games. We held an exhibition, invited external judges and opened voting to students. I also participated as a developer on one of the teams.": "동아리의 첫 게임잼을 기획하고 운영했습니다. 여섯 팀 모두 브라우저 게임을 제출했습니다. 작품 전시회를 열고 외부 심사위원을 초청했으며, 학생들도 투표에 참여할 수 있게 했습니다. 저 역시 한 팀의 개발자로 참가했습니다.",
  "Play all six entries": "여섯 팀의 게임 즐기기",
  "GAME JAM": "게임잼",
  "Student voting board at the first LEVEL0 game jam.": "LEVEL0 첫 게임잼의 학생 투표판.",
  "The first game jam exhibition outdoors.": "야외에서 열린 첫 게임잼 작품 전시회.",
  "Visitors trying games on laptops at the first LEVEL0 game jam exhibition.": "LEVEL0 첫 게임잼 전시회에서 노트북으로 게임을 체험하는 방문객들.",
  "Visitors trying student-made games at the first LEVEL0 game jam exhibition.": "LEVEL0 첫 게임잼 전시회에서 학생들이 만든 게임을 체험하는 방문객들.",
  "Builders beyond our campus": "캠퍼스 밖에서 만난 개발자들",
  "JUL 2026 · REGIONAL BUILD-UP HACKATHON": "2026년 7월 · 지역 연합 빌드업 해커톤",
  "Eight universities": "여덟 개 대학",
  "I helped co-organize a game jam connecting eight universities across Daegu and Gyeongbuk. We coordinated team building, event rules and submissions. This photo is from the July build-up hackathon.": "대구·경북의 여덟 개 대학을 연결하는 게임잼을 공동 기획·운영했습니다. 팀 구성과 행사 규칙, 작품 제출을 함께 조율했습니다. 이 사진은 7월 빌드업 해커톤에서 촬영했습니다.",
  "Photo: Juyoung Park (@juyounginpark)": "사진: 박주영(@juyounginpark)",
  "Explore the collaboration": "연합 활동 살펴보기",
  "CONNECT": "연결",
  "Participants at the regional build-up hackathon.": "지역 연합 빌드업 해커톤 참가자들.",
  "Teams working together during the regional hackathon.": "지역 연합 해커톤에서 함께 작업하는 팀들.",
  "The people behind LEVEL0": "LEVEL0를 함께 만드는 사람들",
  "JUL 2026 · LEVEL0 GROUP PHOTO": "2026년 7월 · LEVEL0 단체 사진",
  "Our people": "함께하는 사람들",
  "I connect makers and create opportunities for them to finish their first games. At the regional jam, I joined fellow LEVEL0 members and supported the event as part of the organizing staff.": "만드는 사람들을 연결하고, 첫 게임을 완성할 기회를 마련합니다. 지역 연합 게임잼에서는 LEVEL0 회원들과 함께하며 운영 스태프로 행사를 지원했습니다.",
  "See the activity records": "활동 기록 보기",
  "TOGETHER": "함께",
  "One club. A window into campus life.": "하나의 동아리로 만나는 대학 생활.",
  "SUMMER 2026 · ADMISSIONS FAIR": "2026년 여름 · 입학박람회",
  "Admissions fair": "입학박람회",
  "WELCOME": "환영합니다",
  "THE ONLY CLUB SELECTED": "유일하게 선정된 동아리",
  "Daegu University selected LEVEL0 as the only student club to take part in its admissions fair, from among its many clubs. We introduced LEVEL0 to high-school students considering university, showing them that campus life can include making games, sharing artwork and creating together.": "대구대학교는 여러 동아리 가운데 LEVEL0를 입학박람회에 참여할 유일한 학생 동아리로 선정했습니다. 대학 진학을 고민하는 고등학생들에게 LEVEL0를 소개하며, 대학 생활에서 게임을 만들고 작품을 나누며 함께 창작할 수 있다는 모습을 보여 주었습니다.",
  "The LEVEL0 booth with visitors, artwork and a game on screen.": "방문객과 작품, 화면 속 게임이 함께한 LEVEL0 부스.",
  "The LEVEL0 booth: games, artwork and a welcome to future students.": "게임과 작품으로 미래의 대학생들을 맞이한 LEVEL0 부스.",
  "A caricature being drawn at the LEVEL0 admissions booth.": "LEVEL0 입학박람회 부스에서 캐리커처를 그리는 모습.",
  "Live drawing at our admissions fair booth.": "입학박람회 부스에서 진행한 현장 드로잉.",
  "Meeting fellow game makers at PlayX4": "PlayX4에서 만난 게임 개발 동료들",
  "MAY · PLAYX4": "5월 · PlayX4",
  "PlayX4 together": "함께한 PlayX4",
  "Our inter-university game development club network visited PlayX4 together. The day brought student game makers beyond their own campuses to explore games and spend time with one another.": "대학 연합 게임 개발 동아리 네트워크가 함께 PlayX4를 방문했습니다. 학생 개발자들이 각자의 캠퍼스를 벗어나 다양한 게임을 살펴보고 서로 교류하는 시간이었습니다.",
  "The game development club network gathered outside KINTEX.": "KINTEX 앞에 모인 게임 개발 동아리 연합.",
  "A group photo outside KINTEX during the PlayX4 visit.": "PlayX4 방문 중 KINTEX 앞에서 찍은 단체 사진.",
  "An activity record combining a shared meal and photos from the expo.": "함께한 식사와 박람회 현장 사진을 모은 활동 기록.",
  "An original activity record: time together and scenes from the expo.": "함께한 시간과 박람회 현장을 담은 원본 활동 기록.",
  "Art made for sharing": "함께 나누는 작품",
  "MAY 26–28, 2026 · ART & CARICATURES": "2026년 5월 26–28일 · 작품 전시와 캐리커처",
  "Art & caricatures": "작품 전시와 캐리커처",
  "LEVEL0 shared artwork and live caricature drawing on campus. Framed illustrations, character prints and hand-drawn portraits brought the club’s creative work out into a space where other students could see it up close.": "LEVEL0는 캠퍼스에서 작품을 전시하고 현장 캐리커처 드로잉을 진행했습니다. 액자에 담은 일러스트와 캐릭터 프린트, 손으로 그린 초상화를 통해 다른 학생들도 동아리의 창작물을 가까이에서 만나볼 수 있게 했습니다.",
  "Visitors at the LEVEL0 art table beside its banner and event sign.": "LEVEL0 배너와 행사 안내판 옆 작품 전시 테이블을 찾은 방문객들.",
  "The exhibition table, with our LEVEL0 banner and live-drawing schedule.": "LEVEL0 배너와 현장 드로잉 일정이 함께 놓인 전시 테이블.",
  "Framed fantasy illustrations and character prints on display.": "전시된 판타지 일러스트 액자와 캐릭터 프린트.",
  "A closer look at the framed illustrations and character prints.": "가까이에서 살펴본 일러스트 액자와 캐릭터 프린트.",
  "Caricatures and hand-drawn characters displayed together.": "함께 전시된 캐리커처와 손으로 그린 캐릭터들.",
  "Portrait sketches and playful characters from the live-drawing activity.": "현장 드로잉에서 탄생한 초상 스케치와 개성 있는 캐릭터들.",
  "The jam starts with a conversation": "대화로 시작하는 게임잼",
  "JUL 2026 · DISCORD KICKOFF": "2026년 7월 · Discord 시작 방송",
  "Discord kickoff": "Discord 시작 방송",
  "The first Discord broadcast introduced our regional game jam to its online community. This behind-the-scenes photo captures the people, laptops and microphone behind the announcement as the event got started.": "첫 Discord 방송을 통해 온라인 커뮤니티에 지역 연합 게임잼을 소개했습니다. 행사의 시작을 알리는 방송 뒤편에서 함께한 사람들과 노트북, 마이크를 담은 사진입니다.",
  "The team presenting a regional game jam announcement over Discord.": "Discord로 지역 연합 게임잼을 안내하는 운영팀.",
  "Behind the scenes of the Discord announcement broadcast.": "Discord 행사 안내 방송의 뒷모습.",
  "Explore the regional jam": "지역 연합 게임잼 살펴보기",
  "FIRST JAM": "첫 게임잼",
  "PLAYX4": "PlayX4",
  "ART & DRAWING": "작품과 드로잉",
  "FUTURE STUDENTS": "미래의 대학생들",
  "ON AIR": "방송 중",
  "OUR PEOPLE": "함께하는 사람들",

  // Gallery projects: complete descriptions and preview explanations.
  "Job Battle": "직업대전",
  "IDEA → UNITY": "아이디어 → Unity",
  "Prototype in development": "개발 중인 프로토타입",
  "Unity · C# · Photon": "Unity · C# · Photon",
  "I defined the game rules and art direction, then iterated on implementation and debugging with Claude Code + Unity MCP. Inspecting the Animator on a character created at runtime helped us trace and fix recurring animation errors.": "게임 규칙과 아트 방향을 정한 뒤 Claude Code + Unity MCP와 함께 구현과 디버깅을 반복했습니다. 실행 중 생성된 캐릭터의 Animator를 살펴보며 반복되는 애니메이션 오류의 원인을 찾아 수정했습니다.",
  "The preview cycles through original Blender character animations: run, attack, defend and idle. In Unity play mode, I verified controller assignment, Idle playback and entry into Attack.": "미리보기에서는 Blender 캐릭터의 원본 달리기·공격·방어·대기 애니메이션을 차례로 보여 줍니다. Unity 플레이 모드에서는 컨트롤러 할당, Idle 재생, Attack 진입을 확인했습니다.",
  "Explore the code": "코드 살펴보기",
  "AI Mafia": "AI 마피아",
  "ONE HUMAN. FIVE AIs.": "사람 한 명, AI 다섯 명.",
  "Team project": "팀 프로젝트",
  "Unity · C# · Ollama · Gemma": "Unity · C# · Ollama · Gemma",
  "One human and five local AI players talk, reason and vote. I developed the game rules, prompts, AI integration and UI. We used Claude during development; the in-game AI runs on Ollama + Gemma.": "사람 한 명과 로컬 AI 플레이어 다섯 명이 대화하고 추리하며 투표합니다. 저는 게임 규칙과 프롬프트, AI 연동, UI를 개발했습니다. 개발 과정에서는 Claude를 활용했고, 게임 속 AI는 Ollama + Gemma로 작동합니다.",
  "The preview cycles through the actual title, discussion and voting screens, both in the frame and here.": "액자와 이 상세 화면의 미리보기에서 실제 타이틀·토론·투표 화면을 차례로 보여 줍니다.",
  "See how it was made": "제작 과정 보기",
  "Lucky Derby": "럭키 더비",
  "PLAY IN YOUR BROWSER": "브라우저에서 바로 플레이",
  "Solo project": "개인 프로젝트",
  "JavaScript · Three.js": "JavaScript · Three.js",
  "A browser racing game with transformations, weather and cinematic camera work. Building with Claude, I refined the camera composition to keep the chasing horses in frame.": "변신과 날씨, 영화 같은 카메라 연출을 담은 브라우저 경마 게임입니다. Claude와 함께 개발하며 뒤따르는 말들도 화면에 잡히도록 카메라 구도를 다듬었습니다.",
  "Actual race screenshots cycle through the start, time-stop skill and booster. You can also play this game in the arcade.": "실제 레이스의 출발·시간 정지 스킬·부스터 장면을 차례로 보여 줍니다. 게임 아케이드에서도 직접 플레이할 수 있습니다.",
  "Play the game": "게임 플레이",
  "Purification Night": "정화의 밤",
  "A NIGHT TO SURVIVE": "살아남아야 하는 밤",
  "Purification Night title screen with the original game logo and menu buttons.": "원본 게임 로고와 메뉴 버튼이 있는 정화의 밤 타이틀 화면.",
  "Unity · C#": "Unity · C#",
  "For this 2D roguelite, I worked on boss patterns, cutscenes, an infinite map, editor testing tools and build checks.": "이 2D 로그라이트 게임에서 보스 패턴과 컷신, 무한 맵, 에디터 테스트 도구, 빌드 점검을 맡았습니다.",
  "The original title background loops while the game logo and menu stay visible.": "게임 로고와 메뉴가 보이는 상태에서 원본 타이틀 배경이 반복 재생됩니다.",
  "Explore the project": "프로젝트 살펴보기",
  "Cooking Genius": "요리왕천재",
  "ONE KEYBOARD. TWO CHEFS.": "키보드 하나, 요리사 두 명.",
  "Team project · Game jam completed": "팀 프로젝트 · 게임잼 완성작",
  "Two players share one keyboard in a cooking showdown with 60-second ingredient rounds. As one of two developers, I built game flow, scoring, inventories, special-card effects, audio and dialogue.": "두 플레이어가 키보드 하나를 함께 사용하며, 60초 동안 재료를 모아 요리 대결을 펼칩니다. 개발자 두 명 중 한 명으로 게임 진행과 채점, 인벤토리, 특수 카드 효과, 오디오, 대화창을 구현했습니다.",
  "Finished for the first LEVEL0 game jam. The actual order, ingredient and two-player gameplay screens cycle in the preview. Find the playable game in the arcade, too.": "LEVEL0 첫 게임잼에서 완성한 게임입니다. 미리보기에서는 실제 주문·재료·2인 플레이 화면을 차례로 보여 줍니다. 게임 아케이드에서도 플레이할 수 있습니다.",
  "See the project": "프로젝트 보기",
  "Desktop Widget Designer": "데스크톱 위젯 디자이너",
  "MAKE YOUR DESKTOP YOUR OWN": "내 취향대로 만드는 바탕화면",
  "Capstone team project · Prototype": "캡스톤 팀 프로젝트 · 프로토타입",
  "Electron · React · TypeScript": "Electron · React · TypeScript",
  "A visual desktop widget editor. For this capstone team project, I developed the editor interface and canvas interactions, including dragging, resizing, multi-selection, snapping and property editing.": "데스크톱 위젯을 시각적으로 편집하는 도구입니다. 캡스톤 팀 프로젝트에서 에디터 인터페이스와 드래그, 크기 조절, 다중 선택, 스냅, 속성 편집 등 캔버스 조작 기능을 개발했습니다.",
  "The Zelda-image demo shows Bézier control points and X/Y 3D rotation in the editor. The preview also cycles through the widget canvas and property inspector.": "젤다 이미지를 사용한 데모에서 에디터의 베지어 제어점과 X/Y축 3D 회전을 확인할 수 있습니다. 미리보기에서는 위젯 캔버스와 속성 패널 화면도 차례로 보여 줍니다.",
  "Explore the editor": "에디터 살펴보기",

  // Arcade cabinets.
  "LEVEL0 GAME JAM": "LEVEL0 게임잼",
  "SIX TEAMS / SIX GAMES": "여섯 팀 / 여섯 게임",
  "Discover six browser games from our very first game jam.": "동아리의 첫 게임잼에서 탄생한 브라우저 게임 여섯 편을 만나보세요.",
  "Explore the jam entries": "게임잼 출품작 보기",
  "LUCKY DERBY": "럭키 더비",
  "BROWSER RACING": "브라우저 경마 게임",
  "Add your names and watch the race unfold. Transformations and weather can change everything.": "이름을 입력하고 레이스를 지켜보세요. 변신과 날씨가 모든 흐름을 바꿀 수 있습니다.",
  "Play Lucky Derby": "럭키 더비 플레이",
  "COOKING GENIUS": "요리왕천재",
  "LOCAL VERSUS / 2 PLAYERS": "로컬 대전 / 2인 플레이",
  "Two players, one keyboard and 60-second ingredient rounds. Made for the first LEVEL0 game jam.": "키보드 하나로 즐기는 2인 대전, 60초 동안 펼쳐지는 재료 수집. LEVEL0 첫 게임잼에서 만든 게임입니다.",
  "Discover Cooking Genius": "요리왕천재 살펴보기",

  // Room names, navigation, instructions and accessibility labels.
  "Builder’s Studio": "빌더의 작업실",
  "AFTER HOURS / AT HOME": "하루 일과를 마치고 / 집에서",
  "Pick a project tape, read the newspaper, or turn on the TV.": "프로젝트 테이프를 고르거나 신문을 읽고, TV도 켜 보세요.",
  "LEVEL0 Clubhouse": "LEVEL0 동아리방",
  "THE CLUBHOUSE": "동아리방",
  "Open a locker or click a photo on the whiteboard.": "사물함을 열거나 화이트보드의 사진을 눌러 보세요.",
  "AI x Works Gallery": "AI x 작업 갤러리",
  "THE MAKING GALLERY": "제작 과정 갤러리",
  "Hover over a frame to bring it to life. Tap to explore on mobile.": "액자 위에 마우스를 올리면 미리보기가 움직입니다. 모바일에서는 눌러서 살펴보세요.",
  "Game Arcade": "게임 아케이드",
  "AFTER HOURS ARCADE": "하루 끝의 게임 아케이드",
  "Pick a cabinet. Insert a coin. Discover a game.": "게임기를 고르고 동전을 넣어 게임을 만나보세요.",
  "3D interior. Click lockers, photographs, framed artwork, project tapes or the newspaper to explore.": "3D 실내 공간입니다. 사물함, 사진, 액자 속 작품, 프로젝트 테이프 또는 신문을 눌러 살펴보세요.",
  "← Campus": "← 캠퍼스",
  "Campus": "캠퍼스",
  "Full room": "방 전체 보기",
  "Objects in this room": "이 방의 사물",
  "View the room from the left": "방을 왼쪽에서 보기",
  "Look around": "둘러보기",
  "View the room from the right": "방을 오른쪽에서 보기",
  "Previous project file": "이전 프로젝트 자료",
  "Next project file": "다음 프로젝트 자료",
  "Close photo and story": "사진과 이야기 닫기",
  "Previous photo": "이전 사진",
  "Next photo": "다음 사진",
  "Photos from this activity": "이 활동의 사진",
  "View photo": "사진 보기",
  "Close artwork details": "작품 상세 닫기",
  "Return to shelf": "선반으로 돌아가기",
  "Return tape to shelf": "테이프를 선반에 돌려놓기",
  "Briefing": "개요",
  "My contribution": "내가 맡은 일",
  "Architecture": "구조",
  "Project file sections": "프로젝트 자료 항목",
  "The program": "프로그램 소개",
  "The project": "프로젝트 소개",
  "RETRIEVING PROJECT FILE…": "프로젝트 자료를 꺼내는 중…",
  "Put the paper back": "신문 돌려놓기",
  "Back to the room": "방으로 돌아가기",
  "POST": "신문",
  "CAREER EDITION": "경력 특집",
  "The newspaper": "신문",
  "TV": "TV",
  "OFF THE CLOCK": "쉬는 시간",
  "Favorite games": "좋아하는 게임",
  "SearchPrice": "밥상머리",
  "Modoo Startup": "모두의 창업",
  "NCP Practicum": "NCP 현장실습",

  // Text painted onto 3D room and cabinet surfaces.
  "LEVEL0 / MAKE SOMETHING TOGETHER": "LEVEL0 / 함께 만들어 가는 곳",
  "LIFE AT LEVEL0": "LEVEL0의 일상",
  "MAKE / SHARE / CONNECT": "만들고 / 나누고 / 연결하다",
  "LET’S BUILD": "함께 만들어요",
  "BUILD / ITERATE": "만들고 / 다듬다",
  "LOCAL AI": "로컬 AI",
  "SELECTED WORKS / 2026": "대표 작품 / 2026",
  "AFTER HOURS": "하루 일과를 마치고",
  "INSERT COIN": "동전을 넣어 주세요",
  "PRESS START / 1 CREDIT": "시작 버튼 / 1회 플레이",
  "COIN": "동전",
  "YUMIN'S ARCADE": "유민의 게임 아케이드",
  "FREE PLAY": "무료 플레이",
  "PRESS TO START": "눌러서 시작",
  "CLICK OR PRESS C · 1 CREDIT": "클릭 또는 C 키 · 1회 플레이",
  "CREDIT 01": "플레이 기회 1회",
  "READY?": "준비됐나요?",
  "READY TO PLAY": "플레이 준비 완료",

  // Standalone fragments used in dynamically composed labels.
  "Game jam completed": "게임잼 완성작",
  "Capstone team project": "캡스톤 팀 프로젝트",
  "Prototype": "프로토타입",
  "Google Cloud Authorized Training": "Google Cloud 공인 교육",
  "Whiteboard": "화이트보드",
  "Whiteboard · ": "화이트보드 · ",
  "LOCKER": "사물함",
  "WHITEBOARD": "화이트보드",
  "SELECTED WORK": "대표 작품",
  "SELECTED WORK / ": "대표 작품 / ",
  "FILE": "자료",
  "FILE / ": "자료 / ",
  "PROJECT ARCHIVES": "프로젝트 기록",
  "PROJECT ARCHIVES / FILE ": "프로젝트 기록 / 자료 ",
  "PROJECT FILE": "프로젝트 자료",
  "PROJECT FILE / ": "프로젝트 자료 / ",
  "Open file": "자료 열기",
  "Open file ": "자료 열기 ",
  "View photo ": "사진 보기 ",
  "project preview": "프로젝트 미리보기",
  " project preview": " 프로젝트 미리보기",
  "preview": "미리보기",
  " preview": " 미리보기"
};
