// English source copy for the studio, newspaper and favorite-games television.
// Dynamic labels are assembled by the shared localization layer.
export const koStudio = {
  'Babsangmeori / SearchPrice': '밥상머리 / SearchPrice',
  'Team project · Five-food prototype': '팀 프로젝트 · 음식 5종 프로토타입',
  'Food classification · Recipe data · KAMIS': '음식 분류 · 레시피 데이터 · KAMIS',
  'Five-food prototype': '음식 5종 프로토타입',
  'A food photograph becomes an estimate of its ingredient costs.': '음식 사진 한 장으로 재료비를 추정합니다.',
  'Ingredient costs are hard to judge from a finished dish or a delivery menu.': '완성된 음식이나 배달 메뉴만 보고 재료비를 가늠하기는 어렵습니다.',
  'I contributed food classification, recipe data and KAMIS price integration to connect a recognized dish with an ingredient-cost estimate.': '인식한 음식의 재료비를 추정할 수 있도록 음식 분류, 레시피 데이터, KAMIS 가격 연동을 담당했습니다.',
  'A prototype covering five Korean foods, developed alongside the 2026 Modoo Startup program. The output is an estimate, not an exact purchase cost.': '2026년 모두의 창업 프로그램과 함께 개발한 한식 5종 프로토타입입니다. 결과는 추정치이며, 실제 구매 비용과는 다를 수 있습니다.',
  'Original prototype screenshot. The percentage shown is one example’s classification confidence.': '실제 프로토타입 화면입니다. 표시된 백분율은 해당 예시의 음식 분류 신뢰도입니다.',
  'Read the project record': '프로젝트 기록 보기',
  'Visit the landing page': '랜딩 페이지 방문하기',
  'StayFinder': 'StayFinder',
  'Personal project · Sole developer': '개인 프로젝트 · 단독 개발',
  'Search · Availability · Filters · Caching': '검색 · 예약 가능 여부 · 필터 · 캐싱',
  'Completed for personal use': '개인용으로 개발 완료',
  'One place to compare accommodation across multiple sources.': '여러 사이트의 숙소를 한곳에서 비교합니다.',
  'Checking prices and available dates meant repeatedly switching between accommodation websites.': '가격과 예약 가능한 날짜를 확인하려면 숙소 사이트를 계속 오가야 했습니다.',
  'I built the tool independently, normalizing results from multiple sources and implementing calendar availability, filters and caching.': '여러 출처의 검색 결과를 같은 형식으로 정리하고, 달력의 예약 가능 여부 표시, 필터, 캐싱 기능까지 혼자 구현했습니다.',
  'A completed personal comparison tool for finding stays that match a location and travel dates.': '원하는 지역과 여행 날짜에 맞는 숙소를 찾는 개인용 비교 도구를 완성했습니다.',
  'Original search interface. Open the project record for the implementation notes.': '실제 검색 화면입니다. 구현 내용은 프로젝트 기록에서 확인할 수 있습니다.',
  'On-Geul': '온글',
  'Team project · Team lead & backend': '팀 프로젝트 · 팀장 및 백엔드',
  'Speech-to-text · Gemini · FastAPI': '음성 인식 · Gemini · FastAPI',
  'Google AI Agent Challenge submission': 'Google AI Agent Challenge 출품작',
  'Turn recordings into structured documents.': '녹음 내용을 구조화된 문서로 만듭니다.',
  'Useful conversations and voice notes still require time to transcribe, organize and turn into a usable document.': '유용한 대화와 음성 메모도 문서로 활용하려면 내용을 받아 적고 정리하는 시간이 필요합니다.',
  'As team lead and backend developer, I implemented speech-to-text, Gemini document generation, FastAPI integration and document status handling.': '팀장과 백엔드 개발자로서 음성 인식, Gemini 문서 생성, FastAPI 연동, 문서 상태 처리를 구현했습니다.',
  'A team submission to the Google AI Agent Challenge. The prototype connects audio input to document generation; persistence work remains.': 'Google AI Agent Challenge에 팀으로 출품했습니다. 음성 입력부터 문서 생성까지 연결한 프로토타입이며, 데이터 영구 저장 작업은 남아 있습니다.',
  'Original audio-upload and document-type selection screen.': '실제 음성 업로드 및 문서 유형 선택 화면입니다.',
  'Explore the code': '코드 살펴보기',
  'NCP 3-Tier Architecture PoC': 'NCP 3계층 아키텍처 PoC',
  'CloudSquare practicum · Individual assignment': 'CloudSquare 현장실습 · 개인 과제',
  'Nginx · Node.js / Express · MySQL': 'Nginx · Node.js / Express · MySQL',
  'Completed training PoC · Jan–Feb 2026': '교육용 PoC 완료 · 2026년 1~2월',
  'Build and deploy a bulletin board across three cloud tiers.': '클라우드 3계층 구조로 게시판을 구현하고 배포했습니다.',
  'A cloud application needs clear boundaries between its web layer, application logic and data.': '클라우드 애플리케이션은 웹 계층, 애플리케이션 로직, 데이터를 명확히 분리해야 합니다.',
  'During my CloudSquare practicum, I designed the Web / WAS / DB structure and implemented authentication, posts, uploads, security settings and deployment.': 'CloudSquare 현장실습에서 Web / WAS / DB 구조를 설계하고 인증, 게시글, 업로드, 보안 설정, 배포를 구현했습니다.',
  'A completed individual NCP training PoC, with GitHub Actions deployment. Production monitoring, recovery and autoscaling were outside the assignment’s scope.': 'GitHub Actions 배포를 포함한 개인 NCP 교육용 PoC를 완성했습니다. 운영 환경의 모니터링, 복구, 오토스케일링은 과제 범위에 포함되지 않았습니다.',
  'Original bulletin board screenshot. The architecture tab explains the cloud setup.': '실제 게시판 화면입니다. 아키텍처 탭에서 클라우드 구성을 확인할 수 있습니다.',
  'Read the practicum record': '현장실습 기록 보기',
  'Modoo Startup · First Cohort': '모두의 창업 · 1기',
  'Modoo Startup': '모두의 창업',
  'Startup program · 2026': '창업 프로그램 · 2026년',
  'Prototype · Landing page · Business plan': '프로토타입 · 랜딩 페이지 · 사업계획서',
  'First-round selection · Final submission complete': '1차 선정 · 최종 제출 완료',
  'The program behind the SearchPrice prototype.': 'SearchPrice 프로토타입을 발전시킨 창업 프로그램입니다.',
  'Take an ingredient-cost idea beyond a pitch and make it concrete enough to evaluate.': '재료비 추정 아이디어를 제안에 그치지 않고 평가할 수 있는 구체적인 결과물로 만드는 과제였습니다.',
  'I helped turn the SearchPrice idea into a focused prototype, a landing page, a business plan and activity reports.': 'SearchPrice 아이디어를 핵심 기능에 집중한 프로토타입, 랜딩 페이지, 사업계획서, 활동 보고서로 구체화하는 데 참여했습니다.',
  'Selected in the first round of the 2026 Modoo Startup program; completed the final submission.': '2026년 모두의 창업 프로그램 1차에 선정되었고, 최종 제출을 완료했습니다.',
  'Original program banner. The SearchPrice tape contains the related product prototype.': '실제 프로그램 배너입니다. 관련 제품 프로토타입은 SearchPrice 테이프에서 볼 수 있습니다.',
  'Read the program record': '프로그램 기록 보기',
  'The idea': '아이디어',
  'A visual editor for composing and shaping desktop widgets.': '데스크톱 위젯을 배치하고 모양을 다듬는 비주얼 편집기입니다.',
  'My role': '내 역할',
  'The result': '결과',
  'The problem': '해결하려던 문제',

  'CloudSquare · Industry Practicum': 'CloudSquare · 산업체 현장실습',
  'Cloud lessons, put into practice.': '배운 클라우드 기술을 실무 과제로.',
  'JAN–FEB 2026': '2026년 1~2월',
  'Practicum completed': '현장실습 완료',
  'An industry internship turned cloud architecture lessons into an individual, working proof of concept.': '산업체 현장실습에서 배운 클라우드 아키텍처를 실제로 동작하는 개인 PoC로 구현했습니다.',
  'During my placement at CloudSquare, I designed and developed an NCP three-tier bulletin-board prototype. I worked on the architecture, Web / WAS / DB implementation, security settings and deployment.': 'CloudSquare 현장실습에서 NCP 3계층 게시판 프로토타입을 설계하고 개발했습니다. 아키텍처, Web / WAS / DB 구현, 보안 설정과 배포를 담당했습니다.',
  'The individual project ran from January 29 to February 11, 2026. It connected Nginx, Node.js / Express and MySQL, with encrypted posts, image delivery and GitHub Actions deployment.': '2026년 1월 29일부터 2월 11일까지 진행한 개인 프로젝트입니다. Nginx, Node.js / Express, MySQL을 연결하고 게시글 암호화, 이미지 전송, GitHub Actions 배포를 구현했습니다.',
  'The bulletin-board prototype developed during my practicum.': '현장실습에서 개발한 게시판 프로토타입입니다.',
  'Daegu Public Data & AI Startup Competition': '대구 공공데이터·AI 창업경진대회',
  'Recognition for public data & AI entrepreneurship.': '공공데이터·AI 창업 아이디어로 수상.',
  'JUL 2026': '2026년 7월',
  'Award recognition': '수상',
  'Received award recognition in the Daegu Public Data & AI Startup Competition.': '대구 공공데이터·AI 창업경진대회에서 수상했습니다.',
  'View the award record': '수상 기록 보기',
  'Cloud Architect Program': '클라우드 아키텍트 교육',
  'An outstanding trainee in cloud architecture.': '클라우드 아키텍처 교육 우수 교육생 선정.',
  '29 OCT–21 NOV 2025': '2025년 10월 29일~11월 21일',
  'DANCE / NAVER Cloud': 'DANCE / NAVER Cloud',
  'Outstanding trainee': '우수 교육생',
  'Selected as an outstanding trainee after studying cloud services and architecture in the DANCE program.': 'DANCE 프로그램에서 클라우드 서비스와 아키텍처를 학습하고 우수 교육생으로 선정되었습니다.',
  'I earned the NCA credential in November 2025 and continued applying this learning in an industry practicum.': '2025년 11월 NCA 자격을 취득했고, 이후 산업체 현장실습에서도 배운 내용을 활용했습니다.',
  'Read the training record': '교육 기록 보기',
  'NCA · Naver Cloud Associate': 'NCA · Naver Cloud Associate',
  'Cloud foundations, certified.': '클라우드 기초 역량을 자격으로.',
  'NOV 2025': '2025년 11월',
  'NAVER Cloud': 'NAVER Cloud',
  'Certification earned': '자격 취득',
  'Earned the Naver Cloud Associate certification while building my foundation in cloud services and architecture.': '클라우드 서비스와 아키텍처의 기초를 쌓으며 Naver Cloud Associate 자격을 취득했습니다.',
  'View the credential record': '자격 기록 보기',
  'Computer Literacy · Level 2': '컴퓨터활용능력 · 2급',
  'APR 2022': '2022년 4월',
  'Level 2': '2급',
  'Earned a Level 2 computer literacy credential.': '컴퓨터활용능력 2급을 취득했습니다.',
  'Korean History · Level 2': '한국사능력검정 · 2급',
  'OCT 2021': '2021년 10월',
  'Earned a Level 2 Korean history credential.': '한국사능력검정 2급을 취득했습니다.',
  'Google Cloud AI Agent Challenge Course': 'Google Cloud AI Agent Challenge 교육',
  'Learning to build with AI agents.': 'AI 에이전트로 만드는 법을 배우다.',
  'ISSUED 05 JUN 2026': '2026년 6월 5일 발급',
  'iCORE E&C · Google Cloud Authorized Training': 'iCORE E&C · Google Cloud 공인 교육',
  'Course completed': '교육 수료',
  'Completed the Google Cloud AI Agent Challenge course.': 'Google Cloud AI Agent Challenge 교육을 수료했습니다.',
  'My On-Geul project record documents the course completion alongside the team’s AI-assisted audio-to-document project.': '온글 프로젝트 기록에 교육 수료 내역과 AI로 음성을 문서로 변환한 팀 프로젝트를 함께 정리했습니다.',
  'Read the course & project record': '교육 및 프로젝트 기록 보기',
  'Practical Service Building with LLMs': 'LLM을 활용한 실용 서비스 개발',
  'Turning LLMs into practical services.': 'LLM을 실제로 쓰는 서비스로.',
  'AUG 2025': '2025년 8월',
  'Training completed': '교육 수료',
  'Completed the first and second rounds of training in building practical services with large language models.': '대규모 언어 모델을 활용한 실용 서비스 개발 교육 1·2차를 수료했습니다.',
  'View the training record': '교육 기록 보기',
  'Bohun Medical Ideas Contest': '보훈 의료 아이디어 공모전',
  'An early award for a medical idea.': '일찍이 의료 아이디어로 수상하다.',
  'OCT–NOV 2018': '2018년 10~11월',
  'Encouragement Award': '장려상',
  'Received an Encouragement Award in the Bohun medical ideas competition.': '보훈 의료 아이디어 공모전에서 장려상을 받았습니다.',

  'Zenless Zone Zero': '젠레스 존 제로',
  'The Legend of Zelda: Breath of the Wild': '젤다의 전설: 야생의 숨결',
  'Zelda: Breath of the Wild': '젤다: 야생의 숨결',
  'The Legend of Zelda: Tears of the Kingdom': '젤다의 전설: 왕국의 눈물',
  'Zelda: Tears of the Kingdom': '젤다: 왕국의 눈물',
  'Skul: The Hero Slayer': '스컬',
  'Skul': '스컬',
  'Slay the Spire': '슬레이 더 스파이어',
  'Sekiro: Shadows Die Twice': '세키로: 섀도우 다이 트와이스',
  'Sekiro': '세키로',
  'official artwork': '공식 이미지',
  "YUMIN'S FAVORITES": '유민이 좋아하는 게임',
  'OFF THE CLOCK / MY FAVORITE GAMES': '쉬는 시간 / 내가 좋아하는 게임',
  'Official game page': '공식 게임 페이지',
  'Official game page ↗': '공식 게임 페이지 ↗',
  'Choose a favorite game': '좋아하는 게임 선택',

  'YUMIN / PROJECT ARCHIVES': '유민 / 프로젝트 아카이브',
  'SearchPrice': 'SearchPrice',
  'VHS / FILE': 'VHS / 파일',
  'FILE': '파일',
  'Open file': '파일 열기',
  'Open file ·': '파일 열기 ·',
  'AFTER HOURS': '작업을 마친 뒤',
  'TV · My favorite games': 'TV · 내가 좋아하는 게임',
  'SWITCH': 'SWITCH',
  'Console · My favorite games': '게임기 · 내가 좋아하는 게임',
  'Remote · My favorite games': '리모컨 · 내가 좋아하는 게임',
  'THE VIDEO ARCHIVE': '비디오 아카이브',
  'Notebook · Desktop Widget Designer': '노트 · 데스크톱 위젯 디자이너',
  'NCP / SIMPLIFIED ARCHITECTURE': 'NCP / 간략한 아키텍처',
  'From request to record.': '요청부터 데이터 저장까지.',
  'WEB': 'WEB',
  'WAS': 'WAS',
  'DATA': '데이터',
  'Nginx': 'Nginx',
  'Load balancer': '로드 밸런서',
  'Node.js / Express': 'Node.js / Express',
  'MySQL': 'MySQL',
  'KMS': 'KMS',
  'Post encryption': '게시글 암호화',
  'Object Storage → Global Edge': 'Object Storage → Global Edge',
  'Image delivery': '이미지 전송',
  'GitHub Actions · Deployment': 'GitHub Actions · 배포',

  'Front page': '1면',
  'Certifications': '자격',
  'Learning': '배움',
  'Honors': '수상',
  'Fieldwork': '현장실습',
  'CERTIFICATIONS': '자격',
  'LEARNING': '배움',
  'HONORS': '수상',
  'FIELDWORK': '현장실습',
  'Read the source': '원문 보기',
  'MORE FROM THE STUDIO': '작업실의 다른 소식',
  'On the record.': '기록으로 남긴 발자취.',
  'Qualifications, learning and milestones — collected in one place.': '자격, 배움, 주요 성과를 한곳에 모았습니다.',
  'entry': '건',
  'entries': '건',
  'in this edition.': '이번 호에 실렸습니다.',
  'YUMIN KANG / PERSONAL ARCHIVE': '강유민 / 개인 아카이브',
  'Put the newspaper back': '신문 내려놓기',
  'Close paper': '신문 닫기',
  'CAREER': '활동',
  'EDITION': '특집',
  'CAREER EDITION': '활동 특집',
  // The English masthead splits this optional article from the newspaper name.
  'THE': '',
  'BUILDER POST': '빌더 포스트',
  'THE BUILDER POST': '빌더 포스트',
  'DAEGU': '대구',
  'EST. 2026': '2026년 창간',
  'EXTRA! EXTRA!': '호외! 호외!',
  'LEARNING. MAKING. SHOWING UP.': '배우고. 만들고. 참여하다.',
  'VOL. 01': '제01호',
  'Newspaper sections': '신문 섹션',
  'Yumin Kang · Beyond the projects': '강유민 · 프로젝트 너머의 이야기',
  'END OF EDITION ◼': '이번 호 끝 ◼',
  'The Builder Post · Credentials & milestones': '빌더 포스트 · 자격과 주요 성과',
  'YUMIN KANG / CAREER EDITION': '강유민 / 활동 특집',
  'EXTRA! EXTRA!   /   BEYOND THE PROJECTS': '호외! 호외! / 프로젝트 너머의 이야기',
  'Learning. Making.': '배우고. 만들고.',
  'Showing up.': '참여하다.',
  'ON THE RECORD': '기록으로 남기다',
  'ENTRIES': '건',
  'FIELD NOTES / IN PROGRESS': '현장 기록 / 진행 중',
  'LEARN': '배우기',
  'BUILD': '만들기',
  'SHARE': '나누기',
  'OPEN THE PAPER  /  READ THE STORIES INSIDE': '신문 펼치기 / 안에 담긴 이야기 읽기',
  'The Builder Post · Read the newspaper': '빌더 포스트 · 신문 읽기'
};
