import * as THREE from './vendor/three.module.js';
import {memories,artworks,cabinets} from './room-data.js';
const $=s=>document.querySelector(s);
const INFO={community:{name:'LEVEL0 Clubhouse',en:'THE CLUBHOUSE',hint:'Open a locker or click a photo on the whiteboard.',bg:0xd8dfc9},lab:{name:'Claude × Unity Gallery',en:'THE MAKING GALLERY',hint:'Hover over a frame to bring it to life. Tap to explore on mobile.',bg:0xe0dfd9},arcade:{name:'Game Arcade',en:'AFTER HOURS ARCADE',hint:'Pick a cabinet. Insert a coin. Discover a game.',bg:0x181a2b}};
export class RoomController{
 constructor({onExit}){this.onExit=onExit;this.rooms={};this.opened=false;this.hovered=null;this.selected=null;this.coinState='idle';this.reduced=false;this.angle=0;this.view=new THREE.Vector3();this.target=new THREE.Vector3();this.ray=new THREE.Raycaster();this.pointer=new THREE.Vector2();this.project=new THREE.Vector3();this.clock=performance.now();this.loadTextures=new THREE.TextureLoader();this.textureCache=new Map();
 document.body.insertAdjacentHTML('beforeend',`<dialog id="interior" aria-labelledby="room-title"><div id="room-viewport" tabindex="0" aria-label="3D interior. Click lockers, photographs or framed artwork to explore."></div><div class="room-shade"></div><header class="room-topbar"><button id="leave-room">← Campus</button><div><span id="room-eyebrow"></span><h2 id="room-title"></h2></div><button id="room-wide" class="hidden">Full room</button></header><div id="room-hint"></div><nav id="room-object-list" aria-label="Objects in this room"></nav><div class="room-camera"><button id="room-left" aria-label="View the room from the left">↶</button><span>Look around</span><button id="room-right" aria-label="View the room from the right">↷</button></div><div id="room-tooltip" hidden></div><div id="animated-art" aria-hidden="true"><img alt=""></div><aside id="memory-view" hidden aria-labelledby="memory-title"></aside><div id="cabinet-ui" hidden></div><div id="room-transition" aria-hidden="true"></div></dialog>`);
 this.dialog=$('#interior');this.viewport=$('#room-viewport');
 $('#leave-room').onclick=()=>this.close();$('#room-wide').onclick=()=>this.wide();$('#room-left').onclick=()=>this.turn(-1);$('#room-right').onclick=()=>this.turn(1);
 this.dialog.addEventListener('cancel',e=>{e.preventDefault();if(this.selected)this.wide();else this.close();});
 this.dialog.addEventListener('click',e=>{const object=e.target.closest('[data-object]');if(object)this.activate(object.dataset.object);if(e.target.closest('[data-close-memory]'))this.closeMemory();if(e.target.closest('[data-coin]'))this.insertCoin();});
 this.dialog.addEventListener('pointerover',e=>{const o=e.target.closest('[data-object]');if(o)this.setHover(o.dataset.object);});this.dialog.addEventListener('focusin',e=>{const o=e.target.closest('[data-object]');if(o)this.setHover(o.dataset.object);});
 this.viewport.addEventListener('pointermove',e=>this.pointerMove(e));this.viewport.addEventListener('pointerleave',()=>{if(this.id!=='lab'||!this.selected)this.setHover(null);});this.viewport.addEventListener('pointerdown',e=>{this.pointerStart=[e.clientX,e.clientY];});this.viewport.addEventListener('pointerup',e=>{if(this.pointerStart&&Math.hypot(e.clientX-this.pointerStart[0],e.clientY-this.pointerStart[1])<8){const hit=this.hit(e);if(hit)this.activate(hit);else this.closeMemory();}});
 window.addEventListener('resize',()=>{if(this.renderer)this.resize();});window.addEventListener('keydown',e=>{if(this.opened&&(e.key==='c'||e.key==='C')&&this.id==='arcade'&&this.selected&&this.coinState==='idle'){e.preventDefault();this.insertCoin();}});
 }
 get isOpen(){return this.opened;}
 resetCoin(){if(this.machine){this.machine.coin.visible=false;this.machine.coin.position.set(.72,2.7,1.38);this.machine.coin.rotation.z=0;}this.coinState='idle';}
 open(id,reduced=false){this.resetCoin();this.reduced=reduced;this.id=id;$('#room-tooltip').hidden=true;this.selected=null;this.coinState='idle';this.angle=0;this.setHover(null);this.closeMemory();$('#cabinet-ui').hidden=true;$('#cabinet-ui').innerHTML='';$('#room-wide').classList.add('hidden');$('#interior').dataset.room=id;$('#room-title').textContent=INFO[id].name;$('#room-eyebrow').textContent=INFO[id].en;$('#room-hint').textContent=INFO[id].hint;this.dialog.showModal();this.opened=true;
 if(!this.renderer){this.renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.8));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.1;this.viewport.appendChild(this.renderer.domElement);this.camera=new THREE.OrthographicCamera(-14,14,10,-10,.1,150);requestAnimationFrame(t=>this.tick(t));}
 if(!this.rooms[id])this.rooms[id]=this.build(id);this.room=this.rooms[id];this.renderer.setClearColor(INFO[id].bg);this.renderObjectList();this.resize();this.resetCamera(true);this.viewport.focus({preventScroll:true});$('#room-transition').classList.add('entering');setTimeout(()=>$('#room-transition').classList.remove('entering'),400);
 }
 close(){this.resetCoin();$('#room-tooltip').hidden=true;this.opened=false;this.selected=null;this.hovered=null;$('#animated-art').style.display='none';$('#cabinet-ui').innerHTML='';this.dialog.close();this.onExit?.();}
 wide(){this.resetCoin();this.selected=null;this.coinState='idle';$('#cabinet-ui').hidden=true;$('#cabinet-ui').innerHTML='';$('#room-wide').classList.add('hidden');this.closeMemory();this.setHover(null);this.renderObjectList();this.resetCamera();this.viewport.focus({preventScroll:true});}
 turn(direction){this.angle=THREE.MathUtils.clamp(this.angle+direction*.22,-.45,.45);if(this.selected&&this.id==='arcade')this.wide();this.resetCamera();}
 resetCamera(immediate=false){this.target.set(0,2.15,0);const a=this.id==='arcade'?0:.48;this.view.set(Math.sin(a+this.angle)*23,13,Math.cos(a+this.angle)*23);if(immediate){this.camera.position.copy(this.view);this.look=new THREE.Vector3().copy(this.target);this.camera.zoom=1;this.camera.updateProjectionMatrix();}this.targetZoom=1;}
 resize(){const w=this.viewport.clientWidth,h=this.viewport.clientHeight;this.renderer.setSize(w,h);const aspect=w/h;const half=w<700?13.2/aspect:Math.max(11,14/aspect);this.camera.left=-half*aspect;this.camera.right=half*aspect;this.camera.top=half;this.camera.bottom=-half;this.camera.updateProjectionMatrix();if(this.id==='arcade'&&this.selected)this.targetZoom=w<700?6.35:3.4;}
 texture(url){if(!this.textureCache.has(url)){const t=this.loadTextures.load(url,loaded=>{for(const fit of loaded.userData.fitters??[])fit();});t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=4;this.textureCache.set(url,t);}return this.textureCache.get(url);}
 material(color,options={}){return new THREE.MeshStandardMaterial({color,roughness:.77,...options});}
 box(parent,w,h,d,color,x=0,y=0,z=0,options={}){const mesh=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),this.material(color,options));mesh.position.set(x,y,z);mesh.castShadow=true;mesh.receiveShadow=true;parent.add(mesh);return mesh;}
 cylinder(parent,r1,r2,h,color,x,y,z){const mesh=new THREE.Mesh(new THREE.CylinderGeometry(r1,r2,h,16),this.material(color));mesh.position.set(x,y,z);mesh.castShadow=true;mesh.receiveShadow=true;parent.add(mesh);return mesh;}
 label(parent,text,w,h,bg,fg,x,y,z,size=70){const canvas=document.createElement('canvas');canvas.width=1024;canvas.height=Math.round(1024*h/w);const ctx=canvas.getContext('2d');ctx.fillStyle=bg;ctx.fillRect(0,0,canvas.width,canvas.height);ctx.font=`700 ${size}px sans-serif`;const fitted=Math.min(size,size*944/Math.max(ctx.measureText(text).width,1),canvas.height*.78);ctx.font=`700 ${fitted}px sans-serif`;ctx.fillStyle=fg;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,512,canvas.height/2);const tex=new THREE.CanvasTexture(canvas);tex.colorSpace=THREE.SRGBColorSpace;const m=new THREE.Mesh(new THREE.PlaneGeometry(w,h),this.material(0xffffff,{map:tex}));m.position.set(x,y,z);parent.add(m);return m;}
 photo(parent,url,w,h,x,y,z){const tex=this.texture(url);const mesh=new THREE.Mesh(new THREE.PlaneGeometry(w,h),this.material(0xffffff,{map:tex,roughness:.55}));const fit=()=>{if(!tex.image?.width)return;const a=tex.image.width/tex.image.height;const b=w/h;mesh.scale.set(a<b?a/b:1,a>b?b/a:1,1);};(tex.userData.fitters??=[]).push(fit);fit();mesh.position.set(x,y,z);parent.add(mesh);return mesh;}
 interact(room,group,id,label){group.userData.object=id;room.clickables.push(group);room.objects.set(id,{group,label});return group;}
 build(id){const scene=new THREE.Scene(),room={scene,clickables:[],objects:new Map(),doors:[],frames:[],machines:[]};scene.background=new THREE.Color(INFO[id].bg);scene.add(new THREE.HemisphereLight(id==='arcade'?0x9c9ddf:0xfff5de,id==='arcade'?0x26233d:0x829277,id==='arcade'?1.25:2.3));const light=new THREE.DirectionalLight(id==='arcade'?0xc3b3ff:0xffefd9,id==='arcade'?2:3.3);light.position.set(-8,16,12);light.castShadow=true;light.shadow.mapSize.set(2048,2048);Object.assign(light.shadow.camera,{left:-16,right:16,top:16,bottom:-16,near:1,far:50});light.shadow.bias=-.001;light.shadow.normalBias=.04;scene.add(light);
 if(id==='community')this.clubhouse(room);if(id==='lab')this.gallery(room);if(id==='arcade')this.arcade(room);return room;}
 floor(room,wallColor,floorColor){const s=room.scene;this.box(s,20,.65,14,0x777b6a,0,-.4,0);this.box(s,20,.15,14,floorColor,0,0,0);this.box(s,20,6.5,.25,wallColor,0,3.2,-7);this.box(s,.25,6.5,14,wallColor,-10,3.2,0);this.box(s,20,.16,.2,0xf2e8cf,0,.3,-6.8);this.box(s,.2,.16,14,0xf2e8cf,-9.8,.3,0);}
 table(room,x,z,w=5,d=2.4){const s=room.scene;this.box(s,w,.18,d,0xc59866,x,1.6,z);for(const dx of[-w/2+.2,w/2-.2])for(const dz of[-d/2+.2,d/2-.2])this.box(s,.13,1.55,.13,0x466250,x+dx,.8,z+dz);}
 chair(room,x,z,rotation=0){const g=new THREE.Group();g.position.set(x,0,z);g.rotation.y=rotation;room.scene.add(g);this.box(g,.95,.16,.9,0x84966f,0,.9,0);this.box(g,.95,.7,.14,0x84966f,0,1.4,-.4);for(const a of[-.35,.35])for(const b of[-.3,.3])this.box(g,.08,.9,.08,0x4b6354,a,.43,b);}
 plant(room,x,z){this.cylinder(room.scene,.45,.32,.65,0xc88869,x,.35,z);for(let i=0;i<5;i++){const leaf=new THREE.Mesh(new THREE.SphereGeometry(.5,7,5),this.material(i%2?0x7d9c6b:0x517b59));leaf.scale.set(.45,1.8,.7);leaf.position.set(x+Math.sin(i*2)*.24,1.05+Math.cos(i*2)*.15,z+Math.cos(i*2)*.24);leaf.rotation.z=Math.sin(i*2)*.45;leaf.castShadow=true;room.scene.add(leaf);}}
 clubhouse(room){const s=room.scene;this.floor(room,0xe7e8d5,0xba9c75);for(let i=-9;i<=9;i++)this.box(s,.035,.01,13.9,0xa48b69,i,.081,0);this.label(s,'LEVEL0 / MAKE SOMETHING TOGETHER',11,.65,'#e7e8d5','#46604a',0,5.95,-6.83,59);
 memories.forEach((m,i)=>{const g=new THREE.Group();g.position.set(-7.9+i*2.12,0,-5.9);s.add(g);this.box(g,1.92,4.7,1.6,m.color,0,2.4,0);this.box(g,1.7,4.3,.12,0x344a3e,0,2.4,.81);this.box(g,1.7,.12,1.4,0xd3c7a5,0,1.8,.1);this.box(g,1.7,.12,1.4,0xd3c7a5,0,3.9,.1);this.photo(g,m.image,1.43,1.35,0,2.97,.9);this.box(g,.7,.6,.6,0xe0c7a0,-.2,2.16,.48);this.label(g,m.no,.4,.26,'#294b3d','#f1e2b2',-.15,2.2,.795,300);
 const hinge=new THREE.Group();hinge.position.set(-.94,0,.88);g.add(hinge);this.box(hinge,1.85,4.65,.12,m.color,.925,2.4,0);this.box(hinge,.1,.43,.15,0xeff0ce,1.64,2.5,.13);for(let k=0;k<4;k++)this.box(hinge,1.1,.045,.01,0x3d5848,.9,4.35-k*.12,.068);this.label(hinge,m.no,.58,.43,'#edf0cd','#304739',.925,3.34,.07,300);this.label(hinge,['BEGIN','GAME JAM','CONNECT','TOGETHER'][i],1.4,.26,'#e2e4cc','#3b5644',.93,1.2,.07,108);hinge.userData.open=false;room.doors.push(hinge);this.interact(room,g,m.id,m.label);room.objects.get(m.id).door=hinge;});
 // Whiteboard with actual memories pinned to it.
 this.box(s,7.8,4.2,.2,0x7f8d79,5.7,3.08,-6.65);this.box(s,7.5,3.92,.1,0xf5f1df,5.7,3.08,-6.5);this.label(s,'OUR FIRSTS',5.2,.5,'#f5f1df','#365a49',5.5,4.58,-6.41,120);
 const wallPhotos=[{image:'./assets/community/gaenojam-outdoor-exhibition.png',x:3.55,y:3.27,mid:1,name:'Whiteboard · Outdoor exhibition'},{image:'./assets/community/daegyeongjam-team-work.jpg',x:5.7,y:2.98,mid:2,name:'Whiteboard · Building together'},{image:'./assets/community/daegyeongjam-level0-group.jpg',x:7.85,y:3.35,mid:3,name:'Whiteboard · LEVEL0 group photo'}];wallPhotos.forEach((p,i)=>{const g=new THREE.Group();g.position.set(p.x,p.y,-6.37);g.rotation.z=[.035,-.07,.035][i];s.add(g);this.box(g,1.97,1.83,.025,0xffffff,0,0,0);this.photo(g,p.image,1.78,1.48,0,.075,.022);this.label(g,['FIRST JAM','BUILD TOGETHER','LEVEL0'][i],1.77,.22,'#ffffff','#4c654a',0,-.75,.025,102);this.cylinder(g,.065,.065,.07,[0xce8465,0xc7d376,0x7e9bad][i],0,.86,.045).rotation.x=Math.PI/2;this.interact(room,g,'photo'+i,p.name);Object.assign(room.objects.get('photo'+i),{memory:memories[p.mid],photo:p.image});});
 this.label(s,'6 TEAMS. 6 GAMES. FIRST OF MANY.',6,.3,'#f5f1df','#8a795e',5.65,1.65,-6.4,72);this.box(s,7.8,.12,.45,0x7f8d79,5.7,.96,-6.35);
 this.table(room,1.7,1.0,6,2.5);this.chair(room,.2,3.0,Math.PI);this.chair(room,3,3,Math.PI);this.chair(room,.2,-.9);this.chair(room,3,-.9);
 for(let i=0;i<3;i++){const paper=this.box(s,.75,.018,1,0xf5ecd6,.5+i*.85,1.71,1.23);paper.rotation.y=i*.28;this.box(s,.3,.12,.45,[0xd69375,0xa5bb84,0x8d9fb1][i],-.65,1.78,.5+i*.45);}
 this.box(s,1.25,.08,.85,0x5a7064,3.1,1.75,.75);const laptop=this.box(s,1.25,.82,.065,0x385048,3.1,2.16,.29);laptop.rotation.x=-.15;this.label(s,'LET’S BUILD',1.07,.59,'#c6dba4','#315448',3.1,2.17,.345,120);
 this.cylinder(s,.14,.11,.3,0xf7e4c3,1.8,1.87,.7);this.box(s,3.5,.55,1.2,0x8a9a76,-6.7,.9,3.5);this.box(s,3.5,1,.3,0x8a9a76,-6.7,1.43,3);for(const x of[-8.5,-4.9])this.box(s,.35,.85,1.5,0x718565,x,1.15,3.45);this.plant(room,8.5,4.3);
 // Window on the open side wall.
 this.box(s,.08,2.7,4.2,0x9fbab1,-9.82,3.6,.2);this.box(s,.14,2.95,.12,0xf5edd8,-9.72,3.6,.2);for(const z of[-1.98,2.38])this.box(s,.14,2.95,.16,0xf5edd8,-9.72,3.6,z);this.box(s,.14,.12,4.4,0xf5edd8,-9.72,3.6,.2);
 }
 gallery(room){const s=room.scene;this.floor(room,0xf1efe8,0xd1cdbf);for(let x=-9;x<10;x+=2)for(let z=-6;z<7;z+=2)this.box(s,1.97,.015,1.97,((x+z)%4)?0xd9d5c8:0xd3cfc2,x,.086,z);this.label(s,'CLAUDE × UNITY',11,.76,'#f1efe8','#424d47',0,5.75,-6.83,85);
 artworks.forEach((art,i)=>{const g=new THREE.Group();g.position.set(-7.35+i*4.9,3.75,-6.53);s.add(g);this.box(g,4.28,2.68,.22,0x45493f,0,0,0);this.box(g,4.08,2.48,.08,0xf9f4e4,0,0,.14);const picture=this.photo(g,art.image,3.87,2.18,0,0,.2);this.label(g,art.title,3.5,.34,'#f1efe8','#464f44',0,-1.73,.02,115);this.label(g,art.type+' · '+art.tools,4.1,.21,'#f1efe8','#7b8276',0,-2.05,.02,48);this.interact(room,g,art.id,art.title);room.frames.push({group:g,picture,art,z:g.position.z});
 this.box(s,.12,.42,.12,0x5b6257,g.position.x,5.98,-5.9);const lamp=this.cylinder(s,.2,.24,.32,0x4b5048,g.position.x,5.65,-5.9);lamp.rotation.x=.45;const spot=new THREE.SpotLight(0xffefcd,15,9,.7,.75);spot.position.set(g.position.x,5.6,-4.8);spot.target.position.set(g.position.x,3.75,-6.5);s.add(spot,spot.target);
 });
 // Sculpture plinths and a sketch desk keep the gallery a physical room.
 this.box(s,2.1,1.0,2.1,0xf2eee4,-3.7,.57,.1);const cube=this.box(s,1.03,1.03,1.03,0xb1bc8a,-3.7,1.65,.1);cube.rotation.set(.15,.5,.08);room.sculpture=cube;this.label(s,'BUILD / ITERATE',1.5,.2,'#f2eee4','#67715e',-3.7,.67,1.16,95);
 this.box(s,2.5,1.0,2.1,0xf2eee4,3.6,.57,.1);this.box(s,1.4,.92,.15,0x364b40,3.6,1.62,.1);this.photo(s,'./assets/projects/ai-mafia-day-talk.png',1.26,.71,3.6,1.63,.184);this.box(s,.12,.32,.12,0x364b40,3.6,1.14,.1);this.label(s,'LOCAL AI',1.8,.2,'#f2eee4','#67715e',3.6,.65,1.16,110);
 this.box(s,5,.18,1.1,0x8d927d,0,1.0,4.2);for(const x of[-2,2])this.box(s,.2,.97,.8,0x737966,x,.49,4.2);this.plant(room,8.9,4.8);
 const side=this.photo(s,'./assets/projects/purification-night-cover.png',4.5,2.5,-9.8,3.8,0);side.rotation.y=Math.PI/2;this.label(s,'SELECTED WORKS / 2026',7,.4,'#d1cdbf','#636a5b',0,.095,3.4,90).rotation.x=-Math.PI/2;
 }
 arcade(room){const s=room.scene;this.floor(room,0x24253e,0x242337);for(let x=-9;x<10;x+=2)for(let z=-6;z<7;z+=2)this.box(s,1.98,.014,1.98,((x+z)%4===1)?0x34334b:0x484159,x,.086,z);
 this.label(s,'AFTER HOURS',10,1,'#24253e','#d5a2fb',0,5.85,-6.83,140);this.box(s,16,.08,.08,0xa678c2,0,5.1,-6.73,{emissive:0xac75dc,emissiveIntensity:1.5});
 cabinets.forEach((cab,i)=>{const g=new THREE.Group();g.position.set(-5.5+i*5.5,0,-2.5);s.add(g);this.box(g,3.75,.25,2.8,0x151e27,0,.15,0);this.box(g,3.5,2.9,2.05,cab.color,0,1.69,0);this.box(g,3.5,2.65,1.5,cab.color,0,4.1,-.3);this.box(g,3.65,.85,1.7,0x25283d,0,5.77,-.15);this.box(g,3.72,.1,1.77,cab.glow,0,6.25,-.15,{emissive:cab.glow,emissiveIntensity:.55});this.label(g,cab.title,3.26,.52,'#232638','#faf0d7',0,5.78,.713,110);this.box(g,3.25,2.45,.21,0x101b23,0,4.12,.52);
 const screen=this.label(g,'INSERT COIN',2.99,2.16,'#0a1921','#a8ebce',0,4.12,.641,116);this.label(g,'PRESS START / 1 CREDIT',2.9,.21,'#182b36','#dcdab7',0,2.74,.71,80);this.box(g,3.8,.21,1.4,cab.color,0,2.7,.86);
 const stick=this.cylinder(g,.065,.065,.3,0x232638,-.78,2.97,1.11);const ball=new THREE.Mesh(new THREE.SphereGeometry(.18,12,8),this.material(cab.glow));ball.position.set(-.78,3.19,1.11);g.add(ball);for(let b=0;b<3;b++)this.cylinder(g,.14,.14,.07,[0xe4a185,0xd9d687,0x9bbab0][b],.34+b*.35,2.85,1.15);
 this.box(g,.65,.87,.12,0x1c2932,.68,1.57,1.08);this.box(g,.07,.38,.045,0xbac0ac,.7,1.72,1.159);this.label(g,'COIN',.5,.19,'#1c2932','#dbc583',.69,1.24,1.157,190);this.box(g,1.5,.65,.08,0x25333b,-.55,.67,1.08);for(let l=0;l<5;l++)this.box(g,1.2,.028,.025,0x4f6061,-.55,.86-l*.09,1.132);
 const coin=this.cylinder(g,.16,.16,.038,0xe4c369,.72,2.7,1.38);coin.rotation.x=Math.PI/2;coin.visible=false;this.interact(room,g,cab.id,cab.title);room.machines.push({group:g,screen,coin,cab});const glow=new THREE.PointLight(cab.glow,7,6);glow.position.set(g.position.x,4.4,-1);s.add(glow);
 });
 // Neon wall strips, speakers and waiting stools.
 for(const x of[-9.5,9.5]){this.box(s,.08,4.4,.08,0x9373b7,x,2.7,-6.7,{emissive:0xb68cde,emissiveIntensity:2});this.box(s,1.1,2.4,1,0x161e2b,x*.92,1.3,3);for(const y of[.85,1.8]){const sp=this.cylinder(s,.36,.36,.06,0x485266,x*.92,y,3.55);sp.rotation.x=Math.PI/2;}}
 for(const x of[-5.5,0,5.5]){this.cylinder(s,.6,.6,.18,0x665676,x,1.05,2.55);this.cylinder(s,.07,.07,.94,0x606572,x,.5,2.55);this.cylinder(s,.45,.45,.06,0x454456,x,.08,2.55);}
 }
 renderObjectList(){const data=this.id==='community'?[...memories.map(m=>[m.id,m.no+' '+m.label]),['photo0','Photo · First exhibition'],['photo1','Photo · In the making'],['photo2','Photo · LEVEL0']]:this.id==='lab'?artworks.map(a=>[a.id,a.no+' '+a.title]):cabinets.map((c,i)=>[c.id,'0'+(i+1)+' '+c.title]);$('#room-object-list').innerHTML=data.map(([id,label])=>`<button data-object="${id}" class="${id===this.selected?'active':''}">${label}</button>`).join('');this.dialog.dataset.focused=String(this.id==='arcade'&&!!this.selected);}
 hit(event){const r=this.viewport.getBoundingClientRect();this.pointer.set((event.clientX-r.left)/r.width*2-1,-(event.clientY-r.top)/r.height*2+1);this.ray.setFromCamera(this.pointer,this.camera);const hits=this.ray.intersectObjects(this.room.clickables,true);if(!hits.length)return null;let object=hits[0].object;while(object&&!object.userData.object)object=object.parent;return object?.userData.object??null;}
 pointerMove(event){const id=this.hit(event);this.setHover(id);this.viewport.style.cursor=id?'pointer':'default';const tip=$('#room-tooltip');if(id){tip.hidden=false;tip.textContent=this.room.objects.get(id)?.label??'';tip.style.left=Math.min(event.clientX+16,this.viewport.clientWidth-220)+'px';tip.style.top=(event.clientY+18)+'px';}else tip.hidden=true;}
 setHover(id){if(this.hovered===id)return;this.hovered=id;this.hoverStarted=performance.now();this.slideIndex=-1;const art=this.id==='lab'?artworks.find(a=>a.id===id):null;const overlay=$('#animated-art');if(overlay){overlay.style.display='none';const img=overlay.querySelector('img');if(art?.animation){img.src=art.animation;overlay.style.display='block';}else if(art?.slides){img.src=art.slides[0];overlay.style.display='block';}else img.removeAttribute('src');}}
 activate(id){const item=this.room.objects.get(id);if(!item)return;this.selected=id;this.renderObjectList();if(this.id==='community'){if(item.door)item.door.userData.open=!item.door.userData.open;const m=item.memory??memories.find(m=>m.id===id);this.showMemory(m,item.photo);return;}if(this.id==='lab'){this.setHover(id);const a=artworks.find(a=>a.id===id);this.showArtwork(a);return;}this.focusCabinet(id);}
 showMemory(m,image){$('#memory-view').hidden=false;$('#memory-view').innerHTML=`<button class="memory-close" data-close-memory aria-label="Close photo and story">✕</button><figure><img src="${image??m.image}" alt="${m.title}"><figcaption>${m.date}${m.credit?`<br><a href="${m.creditUrl}" target="_blank" rel="noopener noreferrer">${m.credit}</a>`:''}</figcaption></figure><div class="memory-copy"><span class="memory-kicker">LOCKER / ${m.no}</span><h3 id="memory-title">${m.title}</h3><p>${m.description}</p><a class="memory-link" href="${m.url}" target="_blank" rel="noopener noreferrer">${m.link} ↗</a></div>`;}
 showArtwork(a){$('#memory-view').hidden=false;$('#memory-view').innerHTML=`<button class="memory-close" data-close-memory aria-label="Close artwork details">✕</button><figure><img src="${this.reduced?a.image:(a.animation??a.image)}" alt="${a.title} ${a.animation?'title animation':'screenshot'}"><figcaption>${a.type} · ${a.tools}</figcaption></figure><div class="memory-copy"><span class="memory-kicker">SELECTED WORK / ${a.no}</span><h3 id="memory-title">${a.title}</h3><p>${a.description}</p><p class="art-detail">${a.detail}</p><a class="memory-link" href="${a.url}" target="_blank" rel="noopener noreferrer">${a.link} ↗</a></div>`;}
 closeMemory(){const m=$('#memory-view');if(m){m.hidden=true;m.innerHTML='';}}
 focusCabinet(id){this.resetCoin();this.closeMemory();this.selected=id;this.coinState='idle';this.renderObjectList();this.machine=this.room.machines.find(m=>m.cab.id===id);const x=this.machine.group.position.x;this.target.set(x,3.65,-1.9);this.view.set(x,3.65,22);this.targetZoom=this.viewport.clientWidth<700?6.35:3.4;this.focusTime=performance.now();this.viewport.focus({preventScroll:true});$('#room-wide').classList.remove('hidden');$('#cabinet-ui').hidden=true;$('#cabinet-ui').innerHTML=`<div class="crt-content attract"><div class="crt-topline">YUMIN'S ARCADE <span>FREE PLAY</span></div><p class="crt-title">${this.machine.cab.title}</p><div class="pixel-spark">✦</div><button class="coin-button" data-coin>INSERT COIN <span>PRESS TO START</span></button><p class="crt-caption">CLICK OR PRESS C · 1 CREDIT</p></div><div class="crt-scan" aria-hidden="true"></div>`;}
 insertCoin(){if(this.coinState!=='idle')return;this.coinState='inserting';this.coinStarted=performance.now();this.machine.coin.visible=true;$('#cabinet-ui').innerHTML='<div class="crt-content loading-credit"><span>CREDIT 01</span><strong>READY?</strong><span>···</span></div><div class="crt-scan" aria-hidden="true"></div>';this.chime();}
 chime(){try{const AudioContext=window.AudioContext||window.webkitAudioContext;this.audio??=new AudioContext();const oscillator=this.audio.createOscillator(),gain=this.audio.createGain();oscillator.type='square';oscillator.frequency.setValueAtTime(600,this.audio.currentTime);oscillator.frequency.exponentialRampToValueAtTime(1200,this.audio.currentTime+.1);gain.gain.setValueAtTime(.035,this.audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,this.audio.currentTime+.2);oscillator.connect(gain);gain.connect(this.audio.destination);oscillator.start();oscillator.stop(this.audio.currentTime+.21);}catch{}}
 readyCabinet(){this.coinState='ready';this.machine.coin.visible=false;const c=this.machine.cab;$('#cabinet-ui').innerHTML=`<div class="crt-content game-portal"><div class="crt-topline">CREDIT 01 <span>READY TO PLAY</span></div><a href="${c.url}" target="_blank" rel="noopener noreferrer" class="game-screen-link" aria-label="${c.button}"><img src="${c.image}" alt="${c.title} preview"><span>${c.title}</span></a><p>${c.description}</p><a class="crt-play" href="${c.url}" target="_blank" rel="noopener noreferrer">${c.button} ↗</a></div><div class="crt-scan" aria-hidden="true"></div>`;}
 overlayForPlane(mesh,element,width,height){mesh.updateWorldMatrix(true,false);const geom=mesh.geometry.parameters,w=geom.width,h=geom.height;const points=[[-w/2,h/2,0],[w/2,h/2,0],[-w/2,-h/2,0]].map(p=>{const v=new THREE.Vector3(...p).applyMatrix4(mesh.matrixWorld).project(this.camera);return{x:(v.x*.5+.5)*this.viewport.clientWidth,y:(-v.y*.5+.5)*this.viewport.clientHeight};});const [a,b,c]=points;element.style.width=width+'px';element.style.height=height+'px';element.style.transform=`matrix(${(b.x-a.x)/width},${(b.y-a.y)/width},${(c.x-a.x)/height},${(c.y-a.y)/height},${a.x},${a.y})`;}
 screenBounds(){const screen=this.machine.screen;screen.updateWorldMatrix(true,false);const g=screen.geometry.parameters;const a=new THREE.Vector3(-g.width/2,g.height/2,.015).applyMatrix4(screen.matrixWorld).project(this.camera);const b=new THREE.Vector3(g.width/2,-g.height/2,.015).applyMatrix4(screen.matrixWorld).project(this.camera);const el=$('#cabinet-ui');el.style.left=(a.x*.5+.5)*this.viewport.clientWidth+'px';el.style.top=(-a.y*.5+.5)*this.viewport.clientHeight+'px';el.style.width=(b.x-a.x)*.5*this.viewport.clientWidth+'px';el.style.height=(a.y-b.y)*.5*this.viewport.clientHeight+'px';}
 tick(now){requestAnimationFrame(t=>this.tick(t));const dt=Math.min((now-this.clock)/1000,.04);this.clock=now;if(!this.opened||document.hidden)return;const ease=this.reduced?1:Math.min(dt*6,1);this.camera.position.lerp(this.view,ease);this.look.lerp(this.target,ease);this.camera.lookAt(this.look);this.camera.zoom=THREE.MathUtils.lerp(this.camera.zoom,this.targetZoom,ease);this.camera.updateProjectionMatrix();
 for(const d of this.room.doors)d.rotation.y=THREE.MathUtils.lerp(d.rotation.y,d.userData.open?-1.4:0,ease);
 for(const f of this.room.frames){const hover=f.art.id===this.hovered;const factor=hover&&!this.reduced?1.045:1;f.group.scale.lerp(new THREE.Vector3(factor,factor,factor),ease);f.group.position.z=THREE.MathUtils.lerp(f.group.position.z,f.z+(hover&&!this.reduced?.27:0),ease);f.group.rotation.z=hover&&!this.reduced?Math.sin((now-this.hoverStarted)/650)*.008:0;}
 if(this.room.sculpture&&!this.reduced)this.room.sculpture.rotation.y+=dt*.2;
 const art=this.id==='lab'?artworks.find(a=>a.id===this.hovered):null;if(art?.animation||art?.slides){const f=this.room.frames.find(f=>f.art.id===art.id);if(f){if(art.slides&&!this.reduced){const index=Math.floor((now-this.hoverStarted)/1150)%art.slides.length;if(index!==this.slideIndex){$('#animated-art img').src=art.slides[index];this.slideIndex=index;}}const overlay=$('#animated-art');overlay.style.display=this.reduced?'none':'block';this.overlayForPlane(f.picture,overlay,640,360);}}
 if(this.id==='arcade'&&this.selected){if(now-this.focusTime>360){$('#cabinet-ui').hidden=false;this.screenBounds();}if(this.coinState==='inserting'){const t=Math.min((now-this.coinStarted)/700,1);this.machine.coin.position.y=2.7-t*1.0;this.machine.coin.position.z=1.5-t*.35;this.machine.coin.rotation.z=t*Math.PI*2;if(t===1)this.readyCabinet();}}
 this.renderer.render(this.room.scene,this.camera);
 }
}
