import * as THREE from './vendor/three.module.js';
import {t as translate,localizeCanvas,languageButton,setLocalizedText} from './i18n.js?v=2e590cf41e8e';
import {memories,whiteboardPhotos,artworks,cabinets} from './room-data.js?v=213f48ccc11f';
import {mountArtworkMedia,hasArtworkMotion} from './art-media.js?v=a6f536d82bd4';
import {studioWorks,studioStory,studioLinks} from './studio-data.js?v=ef2422d37e5b';
import {buildStudio,architectureHTML,pickTape,returnTape,tickStudio} from './studio.js?v=942154683d98';
import {favoriteGames} from './favorite-games.js?v=0c87dde84cf3';
import {televisionScreen,televisionLibrary} from './studio-tv.js?v=0cc13d2286f5';
import {newspaperHTML,newspaperEdition,pickNewspaper,returnNewspaper} from './studio-news.js?v=ce5da8f59841';
const $=s=>document.querySelector(s);
const INFO={studio:{name:'Builder’s Studio',en:'AFTER HOURS / AT HOME',hint:'Pick a project tape, read the newspaper, or turn on the TV.',bg:0x202f32},community:{name:'LEVEL0 Clubhouse',en:'THE CLUBHOUSE',hint:'Open a locker or click a photo on the whiteboard.',bg:0xd8dfc9},lab:{name:'AI x Works Gallery',en:'THE MAKING GALLERY',hint:'Hover over a frame to bring it to life. Tap to explore on mobile.',bg:0xe0dfd9},arcade:{name:'Game Arcade',en:'AFTER HOURS ARCADE',hint:'Pick a cabinet. Insert a coin. Discover a game.',bg:0x181a2b}};
export class RoomController{
 constructor({onExit}){this.onExit=onExit;this.rooms={};this.opened=false;this.hovered=null;this.selected=null;this.coinState='idle';this.reduced=false;this.angle=0;this.view=new THREE.Vector3();this.target=new THREE.Vector3();this.ray=new THREE.Raycaster();this.pointer=new THREE.Vector2();this.project=new THREE.Vector3();this.clock=performance.now();this.loadTextures=new THREE.TextureLoader();this.textureCache=new Map();
 document.body.insertAdjacentHTML('beforeend',`<dialog id="interior" aria-labelledby="room-title"><div id="room-viewport" tabindex="0" aria-label="3D interior. Click lockers, photographs, framed artwork, project tapes or the newspaper to explore."></div><div class="room-shade"></div><header class="room-topbar"><button id="leave-room">← Campus</button><div><span id="room-eyebrow"></span><h2 id="room-title"></h2></div><div class="room-top-actions"><button id="room-wide" class="hidden">Full room</button>${languageButton()}</div></header><div id="room-hint"></div><nav id="room-object-list" aria-label="Objects in this room"></nav><div class="room-camera"><button id="room-left" aria-label="View the room from the left">↶</button><span>Look around</span><button id="room-right" aria-label="View the room from the right">↷</button></div><div id="room-tooltip" hidden></div><div id="animated-art" aria-hidden="true"><img alt=""></div><div id="archive-controls" hidden><button data-tape-step="-1" aria-label="Previous project file">←</button><span id="archive-count"></span><button data-tape-step="1" aria-label="Next project file">→</button></div><div id="archive-status" hidden aria-live="polite"></div><div id="studio-screen" hidden></div><section id="tv-library" hidden aria-labelledby="tv-game-title"></section><section id="studio-news" hidden inert aria-labelledby="news-masthead"></section><aside id="memory-view" hidden aria-labelledby="memory-title"></aside><div id="cabinet-ui" hidden></div><div id="room-transition" aria-hidden="true"></div></dialog>`);
 this.dialog=$('#interior');this.viewport=$('#room-viewport');
 $('#leave-room').onclick=()=>this.close();$('#room-wide').onclick=()=>this.wide();$('#room-left').onclick=()=>this.turn(-1);$('#room-right').onclick=()=>this.turn(1);
 this.dialog.addEventListener('cancel',e=>{e.preventDefault();if(this.selected)this.wide();else this.close();});
 this.dialog.addEventListener('click',e=>{const object=e.target.closest('[data-object]');if(object)this.activate(object.dataset.object);if(e.target.closest('[data-close-memory]')){if(this.id==='studio')this.wide();else this.closeMemory();}const stepTape=e.target.closest('[data-tape-step]');if(stepTape){const i=studioWorks.findIndex(w=>w.id===this.studioWork.id);this.activate(studioWorks[(i+Number(stepTape.dataset.tapeStep)+studioWorks.length)%studioWorks.length].id);}const tab=e.target.closest('[data-archive-tab]');if(tab)this.updateArchiveTab(tab.dataset.archiveTab);const game=e.target.closest('[data-tv-game]');if(game)this.selectTVGame(game.dataset.tvGame);if(e.target.closest('[data-close-news]'))this.wide();const newsSection=e.target.closest('[data-news-section]');if(newsSection)this.selectNewsSection(newsSection.dataset.newsSection);if(e.target.closest('[data-coin]'))this.insertCoin();const thumb=e.target.closest('[data-memory-photo]');if(thumb)this.updateMemoryPhoto(Number(thumb.dataset.memoryPhoto));const step=e.target.closest('[data-photo-step]');if(step)this.updateMemoryPhoto(this.memoryPhotoIndex+Number(step.dataset.photoStep));});
 this.dialog.addEventListener('pointerover',e=>{const o=e.target.closest('[data-object]');if(o)this.setHover(o.dataset.object);});this.dialog.addEventListener('focusin',e=>{const o=e.target.closest('[data-object]');if(o)this.setHover(o.dataset.object);});
 this.viewport.addEventListener('pointermove',e=>this.pointerMove(e));this.viewport.addEventListener('pointerleave',()=>{if(this.id!=='lab'||!this.selected)this.setHover(null);});this.viewport.addEventListener('pointerdown',e=>{this.pointerStart=[e.clientX,e.clientY];});this.viewport.addEventListener('pointerup',e=>{if(this.pointerStart&&Math.hypot(e.clientX-this.pointerStart[0],e.clientY-this.pointerStart[1])<8){const hit=this.hit(e);if(hit)this.activate(hit);else if(this.id==='studio'&&this.selected)this.wide();else this.closeMemory();}});
 window.addEventListener('resize',()=>{if(this.renderer)this.resize();});window.addEventListener('keydown',e=>{if(document.querySelector('#language-dialog')?.open||e.altKey||e.ctrlKey||e.metaKey||e.repeat||e.target.isContentEditable||['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName))return;if(this.opened&&this.id==='studio'&&this.studioMode==='tv'&&['ArrowLeft','ArrowRight'].includes(e.code)){e.preventDefault();const i=favoriteGames.findIndex(g=>g.id===this.tvGame.id);this.selectTVGame(favoriteGames[(i+(e.code==='ArrowRight'?1:-1)+favoriteGames.length)%favoriteGames.length].id);}if(this.opened&&e.code==='KeyC'&&this.id==='arcade'&&this.selected&&this.coinState==='idle'){e.preventDefault();this.insertCoin();}});
 }
 get isOpen(){return this.opened;}
 resetCoin(){if(this.machine){this.machine.coin.visible=false;this.machine.coin.position.set(.72,2.7,1.38);this.machine.coin.rotation.z=0;}this.coinState='idle';}
 open(id,reduced=false){this.resetCoin();this.reduced=reduced;this.id=id;$('#room-wide').textContent='Full room';$('#room-tooltip').hidden=true;this.selected=null;this.coinState='idle';this.angle=0;this.setHover(null);this.closeMemory();$('#cabinet-ui').hidden=true;$('#cabinet-ui').innerHTML='';$('#room-wide').classList.add('hidden');$('#interior').dataset.room=id;$('#room-title').textContent=INFO[id].name;$('#room-eyebrow').textContent=INFO[id].en;$('#room-hint').textContent=INFO[id].hint;this.dialog.showModal();this.opened=true;
 if(!this.renderer){this.renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.8));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.1;this.viewport.appendChild(this.renderer.domElement);this.camera=new THREE.OrthographicCamera(-14,14,10,-10,.1,150);requestAnimationFrame(t=>this.tick(t));}
 if(!this.rooms[id])this.rooms[id]=this.build(id);this.room=this.rooms[id];this.renderer.setClearColor(INFO[id].bg);this.renderer.toneMappingExposure=id==='studio'?.92:1.1;this.renderObjectList();this.resize();this.resetCamera(true);this.viewport.focus({preventScroll:true});$('#room-transition').classList.add('entering');setTimeout(()=>$('#room-transition').classList.remove('entering'),400);
 }
 close(){this.resetCoin();this.setHover(null);this.closeMemory();$('#room-tooltip').hidden=true;this.opened=false;this.selected=null;$('#animated-art').style.display='none';$('#cabinet-ui').innerHTML='';this.dialog.close();this.onExit?.();}
 wide(){this.resetCoin();this.selected=null;this.coinState='idle';$('#cabinet-ui').hidden=true;$('#cabinet-ui').innerHTML='';$('#room-wide').classList.add('hidden');this.closeMemory();this.setHover(null);this.renderObjectList();$('#room-hint').textContent=INFO[this.id].hint;this.resetCamera();this.viewport.focus({preventScroll:true});}
 turn(direction){this.angle=THREE.MathUtils.clamp(this.angle+direction*.22,-.45,.45);if(this.selected&&['arcade','studio'].includes(this.id))this.wide();this.resetCamera();}
 resetCamera(immediate=false){this.target.set(0,this.id==='studio'?1.5:2.15,0);const a=this.id==='arcade'?0:this.id==='studio'?.34:.48;const radius=this.id==='studio'?26:23;this.view.set(Math.sin(a+this.angle)*radius,this.id==='studio'?18:13,Math.cos(a+this.angle)*radius);if(immediate){this.camera.position.copy(this.view);this.look=new THREE.Vector3().copy(this.target);this.camera.zoom=1;this.camera.updateProjectionMatrix();}this.targetZoom=1;}
 resize(){const w=this.viewport.clientWidth,h=this.viewport.clientHeight;this.renderer.setSize(w,h);const aspect=w/h;const half=this.id==='studio'?(w<=700?16.2/aspect:Math.max(12.8,16.2/aspect)):(w<700?13.2/aspect:Math.max(11,14/aspect));this.camera.left=-half*aspect;this.camera.right=half*aspect;this.camera.top=half;this.camera.bottom=-half;this.camera.updateProjectionMatrix();if(this.id==='arcade'&&this.selected)this.targetZoom=w<700?6.35:3.4;if(this.id==='studio'&&this.selected)this.positionStudioCamera();}
 texture(url){if(!this.textureCache.has(url)){const t=this.loadTextures.load(url,loaded=>{for(const fit of loaded.userData.fitters??[])fit();});t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=4;this.textureCache.set(url,t);}return this.textureCache.get(url);}
 material(color,options={}){return new THREE.MeshStandardMaterial({color,roughness:.77,...options});}
 box(parent,w,h,d,color,x=0,y=0,z=0,options={}){const mesh=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),this.material(color,options));mesh.position.set(x,y,z);mesh.castShadow=true;mesh.receiveShadow=true;parent.add(mesh);return mesh;}
 cylinder(parent,r1,r2,h,color,x,y,z,segments=16){const mesh=new THREE.Mesh(new THREE.CylinderGeometry(r1,r2,h,segments),this.material(color));mesh.position.set(x,y,z);mesh.castShadow=true;mesh.receiveShadow=true;parent.add(mesh);return mesh;}
 label(parent,text,w,h,bg,fg,x,y,z,size=70){const canvas=document.createElement('canvas');canvas.width=1024;canvas.height=Math.round(1024*h/w);const ctx=canvas.getContext('2d'),tex=new THREE.CanvasTexture(canvas);tex.colorSpace=THREE.SRGBColorSpace;localizeCanvas(canvas,tex,()=>{const label=translate(text);ctx.fillStyle=bg;ctx.fillRect(0,0,canvas.width,canvas.height);ctx.font=`700 ${size}px sans-serif`;const fitted=Math.min(size,size*944/Math.max(ctx.measureText(label).width,1),canvas.height*.78);ctx.font=`700 ${fitted}px sans-serif`;ctx.fillStyle=fg;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(label,512,canvas.height/2);});const m=new THREE.Mesh(new THREE.PlaneGeometry(w,h),this.material(0xffffff,{map:tex}));m.position.set(x,y,z);parent.add(m);return m;}
 photo(parent,url,w,h,x,y,z){const tex=this.texture(url);const mesh=new THREE.Mesh(new THREE.PlaneGeometry(w,h),this.material(0xffffff,{map:tex,roughness:.55}));const fit=()=>{if(!tex.image?.width)return;const a=tex.image.width/tex.image.height;const b=w/h;mesh.scale.set(a<b?a/b:1,a>b?b/a:1,1);};(tex.userData.fitters??=[]).push(fit);fit();mesh.position.set(x,y,z);parent.add(mesh);return mesh;}
 artworkPicture(parent,art,w,h,x,y,z){
  const picture=this.photo(parent,art.image,w,h,x,y,z);
  if(art.layers){
   const oldMaterial=picture.material;picture.material=new THREE.MeshBasicMaterial({map:oldMaterial.map,toneMapped:false});oldMaterial.dispose();
   for(const layer of art.layers){
    const map=this.texture(layer.src);map.magFilter=THREE.NearestFilter;
    const mesh=new THREE.Mesh(new THREE.PlaneGeometry(w*layer.w,h*layer.h),new THREE.MeshBasicMaterial({map,transparent:true,depthWrite:false,toneMapped:false}));
    mesh.position.set(w*(layer.x+layer.w/2-.5),h*(.5-layer.y-layer.h/2),.008);picture.add(mesh);
   }
  }
  return picture;
 }
 interact(room,group,id,label){group.userData.object=id;room.clickables.push(group);room.objects.set(id,{group,label});return group;}
 build(id){const scene=new THREE.Scene(),room={scene,clickables:[],objects:new Map(),doors:[],frames:[],machines:[]};scene.background=new THREE.Color(INFO[id].bg);scene.add(new THREE.HemisphereLight(id==='studio'?0xd7e5e1:id==='arcade'?0x9c9ddf:0xfff5de,id==='studio'?0x48433d:id==='arcade'?0x26233d:0x829277,id==='studio'?1.75:id==='arcade'?1.25:2.3));const light=new THREE.DirectionalLight(id==='arcade'?0xc3b3ff:0xffefd9,id==='studio'?2.35:id==='arcade'?2:3.3);light.position.set(-8,16,12);light.castShadow=true;light.shadow.mapSize.set(2048,2048);Object.assign(light.shadow.camera,{left:-16,right:16,top:16,bottom:-16,near:1,far:50});light.shadow.bias=-.001;light.shadow.normalBias=.04;scene.add(light);
 if(id==='community')this.clubhouse(room);if(id==='lab')this.gallery(room);if(id==='arcade')this.arcade(room);if(id==='studio')buildStudio(this,room);return room;}
 floor(room,wallColor,floorColor){const s=room.scene;this.box(s,20,.65,14,0x777b6a,0,-.4,0);this.box(s,20,.15,14,floorColor,0,0,0);this.box(s,20,6.5,.25,wallColor,0,3.2,-7);this.box(s,.25,6.5,14,wallColor,-10,3.2,0);this.box(s,20,.16,.2,0xf2e8cf,0,.3,-6.8);this.box(s,.2,.16,14,0xf2e8cf,-9.8,.3,0);}
 table(room,x,z,w=5,d=2.4){const s=room.scene;this.box(s,w,.18,d,0xc59866,x,1.6,z);for(const dx of[-w/2+.2,w/2-.2])for(const dz of[-d/2+.2,d/2-.2])this.box(s,.13,1.55,.13,0x466250,x+dx,.8,z+dz);}
 chair(room,x,z,rotation=0){const g=new THREE.Group();g.position.set(x,0,z);g.rotation.y=rotation;room.scene.add(g);this.box(g,.95,.16,.9,0x84966f,0,.9,0);this.box(g,.95,.7,.14,0x84966f,0,1.4,-.4);for(const a of[-.35,.35])for(const b of[-.3,.3])this.box(g,.08,.9,.08,0x4b6354,a,.43,b);}
 plant(room,x,z,scale=1){
  const g=new THREE.Group();g.position.set(x,.02,z);g.scale.setScalar(scale);room.scene.add(g);
  const profile=[[.29,0],[.32,.05],[.41,.63],[.43,.66],[.43,.72],[.36,.72],[.35,.64]].map(([r,y])=>new THREE.Vector2(r,y));
  const pot=new THREE.Mesh(new THREE.LatheGeometry(profile,32),this.material(0xb87857,{side:THREE.DoubleSide}));pot.castShadow=true;pot.receiveShadow=true;g.add(pot);
  this.cylinder(g,.35,.35,.04,0x45352a,0,.65,0);this.cylinder(g,.33,.34,.035,0x9e644a,0,.035,0);
  const branch=(a,b,r)=>{const direction=b.clone().sub(a),m=new THREE.Mesh(new THREE.CylinderGeometry(r*.7,r,direction.length(),9),this.material(0x47633b));m.position.copy(a).add(b).multiplyScalar(.5);m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),direction.normalize());m.castShadow=true;g.add(m);};
  branch(new THREE.Vector3(0,.66,0),new THREE.Vector3(.02,1.77,0),.036);
  for(let i=0;i<7;i++){
   const angle=i*2.4,h=.94+i*.115,base=new THREE.Vector3(0,h,0),tip=new THREE.Vector3(Math.cos(angle)*.24,h+.16,Math.sin(angle)*.24);branch(base,tip,.017);
   const leaf=new THREE.Mesh(new THREE.SphereGeometry(1,14,8),this.material(i%2?0x71905b:0x426a45));leaf.scale.set(.29,.052,.13);leaf.position.copy(tip).add(new THREE.Vector3(Math.cos(angle)*.16,.035,Math.sin(angle)*.16));leaf.rotation.set(0,-angle,.22*Math.cos(angle));leaf.castShadow=true;leaf.receiveShadow=true;g.add(leaf);
  }
  return g;
 }
 clubhouse(room){const s=room.scene;this.floor(room,0xe7e8d5,0xba9c75);for(let i=-9;i<=9;i++)this.box(s,.035,.01,13.9,0xa48b69,i,.081,0);this.label(s,'LEVEL0 / MAKE SOMETHING TOGETHER',11,.65,'#e7e8d5','#46604a',0,5.95,-6.83,59);
 memories.filter(m=>m.locker).forEach((m,i)=>{const g=new THREE.Group();g.position.set(-8.3+i*1.7,0,-5.9);g.scale.x=.8;s.add(g);this.box(g,1.92,4.7,1.6,m.color,0,2.4,0);this.box(g,1.7,4.3,.12,0x344a3e,0,2.4,.81);this.box(g,1.7,.12,1.4,0xd3c7a5,0,1.8,.1);this.box(g,1.7,.12,1.4,0xd3c7a5,0,3.9,.1);this.photo(g,m.image,1.43,1.35,0,2.97,.9);this.box(g,.7,.6,.6,0xe0c7a0,-.2,2.16,.48);this.label(g,m.no,.4,.26,'#294b3d','#f1e2b2',-.15,2.2,.795,300);
 const hinge=new THREE.Group();hinge.position.set(-.94,0,.88);g.add(hinge);this.box(hinge,1.85,4.65,.12,m.color,.925,2.4,0);this.box(hinge,.1,.43,.15,0xeff0ce,1.64,2.5,.13);for(let k=0;k<4;k++)this.box(hinge,1.1,.045,.01,0x3d5848,.9,4.35-k*.12,.068);this.label(hinge,m.no,.58,.43,'#edf0cd','#304739',.925,3.34,.07,300);this.label(hinge,m.sticker,1.4,.26,'#e2e4cc','#3b5644',.93,1.2,.07,108);hinge.userData.open=false;room.doors.push(hinge);this.interact(room,g,m.id,m.label);Object.assign(room.objects.get(m.id),{door:hinge,memory:m});});
 // Whiteboard with actual memories pinned to it.
 this.box(s,7.8,4.2,.2,0x7f8d79,5.7,3.08,-6.65);this.box(s,7.5,3.92,.1,0xf5f1df,5.7,3.08,-6.5);this.label(s,'LIFE AT LEVEL0',5.2,.4,'#f5f1df','#365a49',5.7,4.7,-6.41,105);
 whiteboardPhotos.forEach((p,i)=>{const m=memories.find(m=>m.id===p.memoryId);const g=new THREE.Group();g.position.set(3.15+(i%3)*2.55,3.65-Math.floor(i/3)*1.55,-6.37);g.rotation.z=[.035,-.055,.025,-.04,.04,-.02][i];s.add(g);this.box(g,2.1,1.39,.025,0xffffff,0,0,0);this.photo(g,p.image,1.9,1.06,0,.075,.022);this.label(g,p.label,1.94,.2,'#ffffff','#4c654a',0,-.535,.025,86);this.cylinder(g,.06,.06,.07,[0xce8465,0xc7d376,0x7e9bad][i%3],0,.65,.045).rotation.x=Math.PI/2;this.interact(room,g,p.id,'Whiteboard · '+m.label);const item=room.objects.get(p.id);Object.assign(item,{memory:m,photo:p.image});if(!room.objects.has(m.id))room.objects.set(m.id,item);});
 this.label(s,'MAKE / SHARE / CONNECT',6,.22,'#f5f1df','#8a795e',5.65,1.23,-6.4,65);this.box(s,7.8,.12,.45,0x7f8d79,5.7,.96,-6.35);
 this.table(room,1.7,1.0,6,2.5);this.chair(room,.2,3.0,Math.PI);this.chair(room,3,3,Math.PI);this.chair(room,.2,-.9);this.chair(room,3,-.9);
 for(let i=0;i<3;i++){const paper=this.box(s,.75,.018,1,0xf5ecd6,.5+i*.85,1.71,1.23);paper.rotation.y=i*.28;this.box(s,.3,.12,.45,[0xd69375,0xa5bb84,0x8d9fb1][i],-.65,1.78,.5+i*.45);}
 this.box(s,1.25,.08,.85,0x5a7064,3.1,1.75,.75);const laptop=this.box(s,1.25,.82,.065,0x385048,3.1,2.16,.29);laptop.rotation.x=-.15;this.label(s,'LET’S BUILD',1.07,.59,'#c6dba4','#315448',3.1,2.17,.345,120);
 this.cylinder(s,.14,.11,.3,0xf7e4c3,1.8,1.87,.7);this.box(s,3.5,.55,1.2,0x8a9a76,-6.7,.9,3.5);this.box(s,3.5,1,.3,0x8a9a76,-6.7,1.43,3);for(const x of[-8.5,-4.9])this.box(s,.35,.85,1.5,0x718565,x,1.15,3.45);this.plant(room,8.5,4.3);
 // Window on the open side wall.
 this.box(s,.08,2.7,4.2,0x9fbab1,-9.82,3.6,.2);this.box(s,.14,2.95,.12,0xf5edd8,-9.72,3.6,.2);for(const z of[-1.98,2.38])this.box(s,.14,2.95,.16,0xf5edd8,-9.72,3.6,z);this.box(s,.14,.12,4.4,0xf5edd8,-9.72,3.6,.2);
 }
 gallery(room){const s=room.scene;this.floor(room,0xf1efe8,0xd1cdbf);for(let x=-9;x<10;x+=2)for(let z=-6;z<7;z+=2)this.box(s,1.97,.015,1.97,((x+z)%4)?0xd9d5c8:0xd3cfc2,x,.086,z);this.label(s,'AI x Works Gallery',11,.76,'#f1efe8','#424d47',0,5.75,-6.83,85);
 artworks.forEach((art,i)=>{const side=i>=4;const g=new THREE.Group();g.position.set(side?-9.7:-7.35+i*4.9,3.75,side?-3.5+(i-4)*5.6:-6.53);if(side)g.rotation.y=Math.PI/2;s.add(g);this.box(g,4.28,2.68,.22,0x45493f,0,0,0);this.box(g,4.08,2.48,.08,0xf9f4e4,0,0,.14);const picture=this.artworkPicture(g,art,3.87,2.18,0,0,.2);this.label(g,art.title,3.5,.34,'#f1efe8','#464f44',0,-1.73,.02,115);this.label(g,art.type+' · '+art.tools,4.1,.21,'#f1efe8','#7b8276',0,-2.05,.02,48);this.interact(room,g,art.id,art.title);room.frames.push({group:g,picture,art,base:g.position.clone(),normal:new THREE.Vector3(side?1:0,0,side?0:1)});
 const lampX=side?-9.1:g.position.x,lampZ=side?g.position.z:-5.9;this.box(s,.12,.42,.12,0x5b6257,lampX,5.98,lampZ);const lamp=this.cylinder(s,.2,.24,.32,0x4b5048,lampX,5.65,lampZ);if(side)lamp.rotation.z=-.45;else lamp.rotation.x=.45;const spot=new THREE.SpotLight(0xffefcd,15,9,.7,.75);spot.position.set(side?-8:g.position.x,5.6,side?g.position.z:-4.8);spot.target.position.set(side?-9.5:g.position.x,3.75,side?g.position.z:-6.5);s.add(spot,spot.target);
 });
 // Sculpture plinths and a sketch desk keep the gallery a physical room.
 this.box(s,2.1,1.0,2.1,0xf2eee4,-3.7,.57,.1);const cube=this.box(s,1.03,1.03,1.03,0xb1bc8a,-3.7,1.65,.1);cube.rotation.set(.15,.5,.08);room.sculpture=cube;this.label(s,'BUILD / ITERATE',1.5,.2,'#f2eee4','#67715e',-3.7,.67,1.16,95);
 this.box(s,2.5,1.0,2.1,0xf2eee4,3.6,.57,.1);this.box(s,1.4,.92,.15,0x364b40,3.6,1.62,.1);this.photo(s,'./assets/projects/ai-mafia-day-talk.png',1.26,.71,3.6,1.63,.184);this.box(s,.12,.32,.12,0x364b40,3.6,1.14,.1);this.label(s,'LOCAL AI',1.8,.2,'#f2eee4','#67715e',3.6,.65,1.16,110);
 this.box(s,5,.18,1.1,0x8d927d,0,1.0,4.2);for(const x of[-2,2])this.box(s,.2,.97,.8,0x737966,x,.49,4.2);this.plant(room,8.9,4.8);
 this.label(s,'SELECTED WORKS / 2026',7,.4,'#d1cdbf','#636a5b',0,.095,3.4,90).rotation.x=-Math.PI/2;
 }
 arcade(room){const s=room.scene;this.floor(room,0x24253e,0x242337);for(let x=-9;x<10;x+=2)for(let z=-6;z<7;z+=2)this.box(s,1.98,.014,1.98,((x+z)%4===1)?0x34334b:0x484159,x,.086,z);
 this.label(s,'AFTER HOURS',10,1,'#24253e','#d5a2fb',0,5.85,-6.83,140);this.box(s,16,.08,.08,0xa678c2,0,5.1,-6.73,{emissive:0xac75dc,emissiveIntensity:1.5});
 cabinets.forEach((cab,i)=>{const g=new THREE.Group();g.position.set(-5.5+i*5.5,0,-2.5);s.add(g);this.box(g,3.75,.25,2.8,0x151e27,0,.15,0);this.box(g,3.5,2.9,2.05,cab.color,0,1.69,0);this.box(g,3.5,2.65,1.5,cab.color,0,4.1,-.3);this.box(g,3.65,.85,1.7,0x25283d,0,5.77,-.15);this.box(g,3.72,.1,1.77,cab.glow,0,6.25,-.15,{emissive:cab.glow,emissiveIntensity:.55});this.label(g,cab.title,3.26,.52,'#232638','#faf0d7',0,5.78,.713,110);this.box(g,3.25,2.45,.21,0x101b23,0,4.12,.52);
 const screen=this.label(g,'INSERT COIN',2.99,2.16,'#0a1921','#a8ebce',0,4.12,.641,116);this.label(g,'PRESS START / 1 CREDIT',2.9,.21,'#182b36','#dcdab7',0,2.74,.71,80);this.box(g,3.8,.21,1.4,cab.color,0,2.7,.86);
 const stick=this.cylinder(g,.065,.065,.3,0x232638,-.78,2.97,1.11);const ball=new THREE.Mesh(new THREE.SphereGeometry(.18,12,8),this.material(cab.glow));ball.position.set(-.78,3.19,1.11);g.add(ball);for(let b=0;b<3;b++)this.cylinder(g,.14,.14,.07,[0xe4a185,0xd9d687,0x9bbab0][b],.34+b*.35,2.85,1.15);
 this.box(g,.65,.87,.12,0x1c2932,.68,1.57,1.08);this.box(g,.07,.38,.045,0xbac0ac,.7,1.72,1.159);this.label(g,'COIN',.5,.19,'#1c2932','#dbc583',.69,1.24,1.157,190);this.box(g,1.5,.65,.08,0x25333b,-.55,.67,1.08);for(let l=0;l<5;l++)this.box(g,1.2,.028,.025,0x4f6061,-.55,.86-l*.09,1.132);
 const coin=this.cylinder(g,.16,.16,.038,0xe4c369,.72,2.7,1.38);coin.rotation.x=Math.PI/2;coin.visible=false;this.interact(room,g,cab.id,cab.title);room.machines.push({group:g,screen,coin,cab});const glow=new THREE.PointLight(cab.glow,7,6);glow.position.set(g.position.x,4.4,-1);s.add(glow);
 });
 // Neon wall strips, speakers and waiting stools.
 for(const x of[-9.5,9.5]){this.box(s,.08,4.4,.08,0x9373b7,x,2.7,-6.7,{emissive:0xb68cde,emissiveIntensity:2});this.box(s,1.1,2.4,1,0x161e2b,x*.92,1.3,3);for(const y of[.85,1.8]){const sp=this.cylinder(s,.36,.36,.06,0x485266,x*.92,y,3.55);sp.rotation.x=Math.PI/2;}}
 for(const x of[-5.5,0,5.5]){this.cylinder(s,.6,.6,.18,0x665676,x,1.05,2.55);this.cylinder(s,.07,.07,.94,0x606572,x,.5,2.55);this.cylinder(s,.45,.45,.06,0x454456,x,.08,2.55);}
 }
 renderObjectList(){
  if(this.id==='studio'){
   $('#room-object-list').innerHTML=`<button class="tape-choice news-choice" data-object="home-news"><b>POST</b><span><small>CAREER EDITION</small>The newspaper</span></button><button class="tape-choice tv-choice" data-object="home-tv"><b>TV</b><span><small>OFF THE CLOCK</small>Favorite games</span></button>`+studioWorks.map((w,i)=>`<button class="tape-choice" data-object="${w.id}" aria-label="Open file ${w.title}"><img src="${w.image}" alt=""><span><small>FILE / ${String(i+1).padStart(2,'0')}</small>${w.id==='searchprice'?'SearchPrice':w.id==='modoo'?'Modoo Startup':w.id==='ncp'?'NCP Practicum':w.title}</span></button>`).join('');
  }else{
   const data=this.id==='community'?memories.map(m=>[m.id,m.no+' '+m.label]):this.id==='lab'?artworks.map(a=>[a.id,a.no+' '+a.title]):cabinets.map((c,i)=>[c.id,'0'+(i+1)+' '+c.title]);const selected=this.id==='community'?(this.room.objects.get(this.selected)?.memory?.id??this.selected):this.selected;
   $('#room-object-list').innerHTML=data.map(([id,label])=>`<button data-object="${id}" class="${id===selected?'active':''}">${label}</button>`).join('');
  }
  if(this.viewport.clientWidth<700)$('#room-object-list .active')?.scrollIntoView({block:'nearest',inline:'nearest'});this.dialog.dataset.focused=String(['arcade','studio'].includes(this.id)&&!!this.selected);
 }
 hit(event){const r=this.viewport.getBoundingClientRect();this.pointer.set((event.clientX-r.left)/r.width*2-1,-(event.clientY-r.top)/r.height*2+1);this.ray.setFromCamera(this.pointer,this.camera);const hits=this.ray.intersectObjects(this.room.clickables,true);if(!hits.length)return null;let object=hits[0].object;while(object&&!object.userData.object)object=object.parent;return object?.userData.object??null;}
 pointerMove(event){if(this.id==='studio'&&this.selected){$('#room-tooltip').hidden=true;this.viewport.style.cursor='default';return;}const id=this.hit(event);this.setHover(id);this.viewport.style.cursor=id?'pointer':'default';const tip=$('#room-tooltip');if(id){tip.hidden=false;tip.textContent=this.room.objects.get(id)?.label??'';tip.style.left=Math.min(event.clientX+16,this.viewport.clientWidth-220)+'px';tip.style.top=(event.clientY+18)+'px';}else tip.hidden=true;}
 setHover(id){if(id===null)$('#room-tooltip').hidden=true;if(this.hovered===id)return;this.stopHoverMedia?.();this.stopHoverMedia=null;this.hovered=id;this.hoverStarted=performance.now();const art=this.id==='lab'?artworks.find(a=>a.id===id):null;const overlay=$('#animated-art');overlay.style.display='none';if(art&&hasArtworkMotion(art)&&!this.reduced){this.stopHoverMedia=mountArtworkMedia(overlay,art);overlay.style.display='block';}}
 activate(id){const item=this.room.objects.get(id);if(!item)return;this.selected=id;this.renderObjectList();if(this.id==='studio'){if(['home-tv','home-console','home-remote'].includes(id))this.focusTV();else if(['home-news','home-news-board'].includes(id))this.focusNewspaper();else this.focusStudio(id);return;}if(this.id==='community'){if(item.door)item.door.userData.open=!item.door.userData.open;const m=item.memory??memories.find(m=>m.id===id);this.showMemory(m,item.photo);return;}if(this.id==='lab'){this.setHover(id);const a=artworks.find(a=>a.id===id);this.showArtwork(a);return;}this.focusCabinet(id);}
 showMemory(m,image){this.closeMemory();this.memory=m;this.memoryPhotos=m.photos??[{src:m.image,alt:m.title,caption:m.title}];this.memoryPhotoIndex=Math.max(0,this.memoryPhotos.findIndex(p=>p.src===(image??m.image)));const multiple=this.memoryPhotos.length>1;$('#memory-view').hidden=false;$('#memory-view').innerHTML=`<button class="memory-close" data-close-memory aria-label="Close photo and story">✕</button><figure><img id="memory-photo" src="${this.memoryPhotos[this.memoryPhotoIndex].src}" alt="${this.memoryPhotos[this.memoryPhotoIndex].alt}"><figcaption><span class="memory-date">${m.date}</span><span id="memory-photo-caption"></span>${m.credit?`<a href="${m.creditUrl}" target="_blank" rel="noopener noreferrer">${m.credit}</a>`:''}</figcaption></figure>${multiple?`<div class="album-controls"><button data-photo-step="-1" aria-label="Previous photo">←</button><span id="memory-photo-count" aria-live="polite"></span><button data-photo-step="1" aria-label="Next photo">→</button></div><div class="memory-thumbnails" role="group" aria-label="Photos from this activity">${this.memoryPhotos.map((p,i)=>`<button data-memory-photo="${i}" aria-label="View photo ${i+1}: ${p.alt}" aria-pressed="false"><img src="${p.src}" alt="" loading="lazy"></button>`).join('')}</div>`:''}<div class="memory-copy"><span class="memory-kicker">${m.locker?'LOCKER':'WHITEBOARD'} / ${m.no}</span><h3 id="memory-title">${m.title}</h3>${m.highlight?`<span class="memory-highlight">${m.highlight}</span>`:''}<p>${m.description}</p>${m.url?`<a class="memory-link" href="${m.url}" target="_blank" rel="noopener noreferrer">${m.link} ↗</a>`:''}</div>`;this.updateMemoryPhoto(this.memoryPhotoIndex);$('#memory-view').scrollTop=0;}
 updateMemoryPhoto(index){if(!this.memoryPhotos?.length)return;this.memoryPhotoIndex=(index+this.memoryPhotos.length)%this.memoryPhotos.length;const p=this.memoryPhotos[this.memoryPhotoIndex];$('#memory-photo').src=p.src;$('#memory-photo').alt=p.alt;$('#memory-photo-caption').textContent=p.caption??p.alt;const count=$('#memory-photo-count');if(count)count.textContent=`${this.memoryPhotoIndex+1} / ${this.memoryPhotos.length}`;document.querySelectorAll('[data-memory-photo]').forEach((el,i)=>{const active=i===this.memoryPhotoIndex;el.classList.toggle('active',active);el.setAttribute('aria-pressed',String(active));});}
 showArtwork(a){this.closeMemory();$('#memory-view').hidden=false;$('#memory-view').innerHTML=`<button class="memory-close" data-close-memory aria-label="Close artwork details">✕</button><figure><div data-artwork-media></div><figcaption>${a.type} · ${a.tools}</figcaption></figure><div class="memory-copy"><span class="memory-kicker">SELECTED WORK / ${a.no}</span><h3 id="memory-title">${a.title}</h3><p>${a.description}</p><p class="art-detail">${a.detail}</p><a class="memory-link" href="${a.url}" target="_blank" rel="noopener noreferrer">${a.link} ↗</a></div>`;this.stopDetailMedia=mountArtworkMedia($('#memory-view [data-artwork-media]'),a,{animate:!this.reduced});$('#memory-view').scrollTop=0;}
 closeMemory(){
  this.studioFocusAt=null;this.newsRevealAt=null;returnNewspaper(this.room);const news=$('#studio-news');news.hidden=true;news.inert=true;news.classList.remove('is-ready');news.innerHTML='';returnTape(this.room);this.studioMode=null;delete this.dialog.dataset.studioView;
  for(const id of['archive-controls','archive-status','tv-library']){const el=$('#'+id);if(el)el.hidden=true;}
  this.studioScreen=null;const screen=$('#studio-screen');if(screen){screen.hidden=true;screen.innerHTML='';}this.stopDetailMedia?.();this.stopDetailMedia=null;this.memory=null;this.memoryPhotos=null;const m=$('#memory-view');if(m){m.hidden=true;m.innerHTML='';}
 }
 positionStudioCamera(){
  const w=this.viewport.clientWidth,h=this.viewport.clientHeight,mobile=w<=700,worldWidth=this.camera.right-this.camera.left,worldHeight=this.camera.top-this.camera.bottom;
  let center,eye,pixelX,pixelY;
  if(this.studioMode==='news'){
   center=this.room.news.read.clone();eye=new THREE.Vector3(0,.7,5.2);
   const paperWidth=Math.min(w*.92,1080);this.targetZoom=worldWidth/w*paperWidth/6.12;pixelX=w/2;pixelY=h*.49;
  }else if(this.studioMode==='tv'){
   center=this.room.tvScreen.getWorldPosition(new THREE.Vector3());eye=new THREE.Vector3(0,1.0,6);
   const frameWidth=Math.min(w*.89,(mobile?h*.43:h-290)*1.48);
   this.targetZoom=worldWidth/w*frameWidth/5.15;pixelX=w/2;pixelY=h*(mobile?.29:.40);
  }else{
   if(!this.room?.activeTape)return;const panel=w<=1100?340:390,available=w-panel-56;
   const caseHeight=mobile?Math.min(h*.265,w*.66):Math.min(h*.63,available*1.2);
   this.targetZoom=worldHeight*caseHeight/h/3.63;center=this.room.archivePosition.clone();eye=new THREE.Vector3(1.2,1.8,18);
   pixelX=mobile?w*.5:available*.5+16;pixelY=h*(mobile?.265:.48);
  }
  const right=new THREE.Vector3(eye.z,0,-eye.x).normalize(),up=eye.clone().normalize().cross(right);
  this.target.copy(center).addScaledVector(right,(w/2-pixelX)/w*worldWidth/this.targetZoom).addScaledVector(up,(pixelY/h-.5)*worldHeight/this.targetZoom);this.view.copy(this.target).add(eye);
 }
 focusStudio(id){
  this.closeMemory();const item=this.room.objects.get(id),work=studioWorks.find(w=>w.id===item.workId);this.selected=work.id;this.studioWork=work;this.studioMode='archive';this.dialog.dataset.studioView='archive';
  pickTape(this.room,work.id,this.reduced);this.studioFocusAt=performance.now()+(this.reduced?0:250);this.renderObjectList();this.setHover(null);
  $('#room-wide').classList.remove('hidden');$('#room-wide').textContent='Return to shelf';$('#archive-controls').hidden=false;$('#archive-status').hidden=false;
  const tabs=[['briefing','Briefing'],['contribution','My contribution'],...(work.id==='ncp'?[['architecture','Architecture']]:[])];
  const m=$('#memory-view');m.hidden=false;m.innerHTML=`<button class="memory-close" data-close-memory aria-label="Return tape to shelf">✕</button><div class="memory-copy studio-copy"><span class="memory-kicker">PROJECT ARCHIVES / FILE ${work.no}</span><h3 id="memory-title" tabindex="-1">${work.title}</h3><p class="studio-meta">${work.type}</p>${work.status?`<span class="studio-status">${work.status}</span>`:''}<nav class="archive-tabs" aria-label="Project file sections">${tabs.map(([id,label])=>`<button data-archive-tab="${id}" aria-pressed="false">${label}</button>`).join('')}</nav><div class="archive-project-media" data-archive-media></div><div class="studio-story" data-archive-story></div><div class="studio-links">${studioLinks(work)}</div></div>`;
  this.stopDetailMedia=mountArtworkMedia($('[data-archive-media]'),work,{animate:!this.reduced});m.scrollTop=0;this.updateArchiveTab('briefing');this.updateTapeStatus();$('#memory-title').focus({preventScroll:true});
 }
 updateArchiveTab(tab){
  const work=this.studioWork,story=studioStory(work),host=$('[data-archive-story]');
  if(tab==='architecture')host.innerHTML=architectureHTML();
  else {const parts=tab==='contribution'?story.slice(1):[[work.activity?'The program':'The project',work.description],story[0]];host.innerHTML=parts.map(([label,copy])=>`<section><h4>${label}</h4><p>${copy}</p></section>`).join('');}
  this.dialog.querySelectorAll('[data-archive-tab]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.archiveTab===tab)));
 }
 updateTapeStatus(){
  $('#archive-count').textContent=String(studioWorks.findIndex(w=>w.id===this.studioWork.id)+1).padStart(2,'0')+' / 06';setLocalizedText($('#archive-status'),this.room.tapeState==='pulling'?'RETRIEVING PROJECT FILE…':'PROJECT FILE / '+this.studioWork.title);
 }
 focusNewspaper(){
  this.closeMemory();this.selected='home-news';this.studioMode='news';this.dialog.dataset.studioView='news';this.renderObjectList();this.setHover(null);pickNewspaper(this.room,this.reduced);this.positionStudioCamera();
  $('#room-wide').classList.remove('hidden');$('#room-wide').textContent='Put the paper back';const paper=$('#studio-news');paper.innerHTML=newspaperHTML();paper.classList.toggle('without-motion',this.reduced);paper.hidden=false;paper.scrollTop=0;this.newsRevealAt=performance.now()+(this.reduced?0:820);
 }
 selectNewsSection(section){
  const paper=$('#studio-news'),fromIndex=document.activeElement?.closest('.news-index');$('#news-edition-content').innerHTML=newspaperEdition(section);paper.querySelectorAll('.news-sections [data-news-section]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.newsSection===section)));paper.scrollTop=0;if(fromIndex)paper.querySelector(`.news-sections [data-news-section="${section}"]`)?.focus({preventScroll:true});
 }
 focusTV(){
  this.closeMemory();this.selected='home-tv';this.studioMode='tv';this.dialog.dataset.studioView='tv';this.renderObjectList();this.setHover(null);$('#room-wide').classList.remove('hidden');$('#room-wide').textContent='Back to the room';
  this.studioScreen=this.room.tvScreen;this.selectTVGame(this.tvGame?.id??favoriteGames[0].id);this.positionStudioCamera();$('#tv-game-title').focus({preventScroll:true});
 }
 selectTVGame(id){
  this.tvGame=favoriteGames.find(g=>g.id===id)??favoriteGames[0];this.room.tvScreen.material.map=this.texture(this.tvGame.image);this.room.tvScreen.material.needsUpdate=true;
  $('#studio-screen').hidden=false;$('#studio-screen').innerHTML=televisionScreen(this.tvGame);const library=$('#tv-library');library.hidden=false;if(!library.querySelector('[data-tv-game]'))library.innerHTML=televisionLibrary(this.tvGame);else{library.querySelector('#tv-game-title').textContent=this.tvGame.title;library.querySelector('a').href=this.tvGame.url;library.querySelectorAll('[data-tv-game]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.tvGame===this.tvGame.id)));}
 }

 focusCabinet(id){this.resetCoin();this.closeMemory();this.selected=id;this.coinState='idle';this.renderObjectList();this.machine=this.room.machines.find(m=>m.cab.id===id);const x=this.machine.group.position.x;this.target.set(x,3.65,-1.9);this.view.set(x,3.65,22);this.targetZoom=this.viewport.clientWidth<700?6.35:3.4;this.focusTime=performance.now();this.viewport.focus({preventScroll:true});$('#room-wide').classList.remove('hidden');$('#cabinet-ui').hidden=true;$('#cabinet-ui').innerHTML=`<div class="crt-content attract"><div class="crt-topline">YUMIN'S ARCADE <span>FREE PLAY</span></div><p class="crt-title">${this.machine.cab.title}</p><div class="pixel-spark">✦</div><button class="coin-button" data-coin>INSERT COIN <span>PRESS TO START</span></button><p class="crt-caption">CLICK OR PRESS C · 1 CREDIT</p></div><div class="crt-scan" aria-hidden="true"></div>`;}
 insertCoin(){if(this.coinState!=='idle')return;this.coinState='inserting';this.coinStarted=performance.now();this.machine.coin.visible=true;$('#cabinet-ui').innerHTML='<div class="crt-content loading-credit"><span>CREDIT 01</span><strong>READY?</strong><span>···</span></div><div class="crt-scan" aria-hidden="true"></div>';this.chime();}
 chime(){try{const AudioContext=window.AudioContext||window.webkitAudioContext;this.audio??=new AudioContext();const oscillator=this.audio.createOscillator(),gain=this.audio.createGain();oscillator.type='square';oscillator.frequency.setValueAtTime(600,this.audio.currentTime);oscillator.frequency.exponentialRampToValueAtTime(1200,this.audio.currentTime+.1);gain.gain.setValueAtTime(.035,this.audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,this.audio.currentTime+.2);oscillator.connect(gain);gain.connect(this.audio.destination);oscillator.start();oscillator.stop(this.audio.currentTime+.21);}catch{}}
 readyCabinet(){this.coinState='ready';this.machine.coin.visible=false;const c=this.machine.cab;$('#cabinet-ui').innerHTML=`<div class="crt-content game-portal"><div class="crt-topline">CREDIT 01 <span>READY TO PLAY</span></div><a href="${c.url}" target="_blank" rel="noopener noreferrer" class="game-screen-link" aria-label="${c.button}"><img src="${c.image}" alt="${c.title} preview"><span>${c.title}</span></a><p>${c.description}</p><a class="crt-play" href="${c.url}" target="_blank" rel="noopener noreferrer">${c.button} ↗</a></div><div class="crt-scan" aria-hidden="true"></div>`;}
 overlayForPlane(mesh,element,width,height){mesh.updateWorldMatrix(true,false);const geom=mesh.geometry.parameters,w=geom.width,h=geom.height;const points=[[-w/2,h/2,0],[w/2,h/2,0],[-w/2,-h/2,0]].map(p=>{const v=new THREE.Vector3(...p).applyMatrix4(mesh.matrixWorld).project(this.camera);return{x:(v.x*.5+.5)*this.viewport.clientWidth,y:(-v.y*.5+.5)*this.viewport.clientHeight};});const [a,b,c]=points;element.style.width=width+'px';element.style.height=height+'px';element.style.transform=`matrix(${(b.x-a.x)/width},${(b.y-a.y)/width},${(c.x-a.x)/height},${(c.y-a.y)/height},${a.x},${a.y})`;}
 screenBounds(){const screen=this.machine.screen;screen.updateWorldMatrix(true,false);const g=screen.geometry.parameters;const a=new THREE.Vector3(-g.width/2,g.height/2,.015).applyMatrix4(screen.matrixWorld).project(this.camera);const b=new THREE.Vector3(g.width/2,-g.height/2,.015).applyMatrix4(screen.matrixWorld).project(this.camera);const el=$('#cabinet-ui');el.style.left=(a.x*.5+.5)*this.viewport.clientWidth+'px';el.style.top=(-a.y*.5+.5)*this.viewport.clientHeight+'px';el.style.width=(b.x-a.x)*.5*this.viewport.clientWidth+'px';el.style.height=(a.y-b.y)*.5*this.viewport.clientHeight+'px';}
 tick(now){requestAnimationFrame(t=>this.tick(t));const dt=Math.min((now-this.clock)/1000,.04);this.clock=now;if(!this.opened||document.hidden)return;const ease=this.reduced?1:Math.min(dt*6,1);this.camera.position.lerp(this.view,ease);this.look.lerp(this.target,ease);this.camera.lookAt(this.look);this.camera.zoom=THREE.MathUtils.lerp(this.camera.zoom,this.targetZoom,ease);this.camera.updateProjectionMatrix();this.camera.updateMatrixWorld();
 for(const d of this.room.doors)d.rotation.y=THREE.MathUtils.lerp(d.rotation.y,d.userData.open?-1.4:0,ease);
 for(const f of this.room.frames){const hover=f.art.id===this.hovered;const factor=hover&&!this.reduced?1.045:1;f.group.scale.lerp(new THREE.Vector3(factor,factor,factor),ease);f.group.position.lerp(f.base.clone().addScaledVector(f.normal,hover&&!this.reduced?.27:0),ease);f.group.rotation.z=hover&&!this.reduced?Math.sin((now-this.hoverStarted)/650)*.008:0;}
 if(this.room.sculpture&&!this.reduced)this.room.sculpture.rotation.y+=dt*.2;
 const art=this.id==='lab'?artworks.find(a=>a.id===this.hovered):null;if(art&&hasArtworkMotion(art)&&!this.reduced){const f=this.room.frames.find(f=>f.art.id===art.id);if(f){const p=f.picture,g=p.geometry.parameters;this.overlayForPlane(p,$('#animated-art'),640,640*g.height*p.scale.y/(g.width*p.scale.x));}}
 if(this.id==='studio'){if(this.studioMode==='news'&&this.newsRevealAt!==null&&now>=this.newsRevealAt){this.newsRevealAt=null;const paper=$('#studio-news');paper.classList.add('is-ready');paper.inert=false;$('#news-masthead').focus({preventScroll:true});}if(this.studioFocusAt!==null&&now>=this.studioFocusAt&&this.selected){this.positionStudioCamera();this.studioFocusAt=null;}const before=this.room.tapeState;tickStudio(this,this.room,now,dt,ease);if(before!==this.room.tapeState&&this.studioMode==='archive')this.updateTapeStatus();}
 if(this.id==='studio'&&this.studioMode==='tv'&&this.studioScreen){this.overlayForPlane(this.studioScreen,$('#studio-screen'),1000,569);}
 if(this.id==='arcade'&&this.selected){if(now-this.focusTime>360){$('#cabinet-ui').hidden=false;this.screenBounds();}if(this.coinState==='inserting'){const t=Math.min((now-this.coinStarted)/700,1);this.machine.coin.position.y=2.7-t*1.0;this.machine.coin.position.z=1.5-t*.35;this.machine.coin.rotation.z=t*Math.PI*2;if(t===1)this.readyCabinet();}}
 this.renderer.render(this.room.scene,this.camera);
 }
}
