export const memories=[
 {id:'founding',no:'01',title:'The first page of LEVEL0',date:'AUG 2025 · FOUNDING THE CLUB',image:'./assets/community/level0-recruitment-poster.png',label:'The beginning',description:'I brought together people at Daegu University who wanted to make games. As the founding president, I led recruitment, role allocation and team formation. Around 30 members joined us at the start.',url:'https://app.notion.com/p/086cea20cae18291a3de016079ace80c',link:'Read the founding story',color:0x7d9a76},
 {id:'firstjam',no:'02',title:'Our first jam. Six finished games.',date:'MAY 2026 · LEVEL0 FIRST GAME JAM',image:'./assets/community/gaenojam-voting-board.jpg',label:'Our first game jam',description:'I planned and ran our first game jam. All six teams submitted browser games. We held an exhibition, invited external judges and opened voting to students. I also participated as a developer on one of the teams.',url:'https://itch.io/jam/level0-firstjam-gaenojam',link:'Play all six entries',color:0xd48968},
 {id:'alliance',no:'03',title:'Builders beyond our campus',date:'JUL 2026 · REGIONAL BUILD-UP HACKATHON',image:'./assets/community/daegyeongjam-all-participants.jpg',label:'Eight universities',description:'I helped co-organize a game jam connecting eight universities across Daegu and Gyeongbuk. We coordinated team building, event rules and submissions. This photo is from the July build-up hackathon.',credit:'Photo: Juyoung Park (@juyounginpark)',creditUrl:'https://www.instagram.com/juyounginpark/p/Db0hXoAILwp/',url:'https://app.notion.com/p/de8cea20cae1834ab16c818368f5fd15',link:'Explore the collaboration',color:0x7c91ad},
 {id:'together',no:'04',title:'The people behind LEVEL0',date:'JUL 2026 · LEVEL0 GROUP PHOTO',image:'./assets/community/daegyeongjam-level0-group.jpg',label:'Our people',description:'I connect makers and create opportunities for them to finish their first games. At the regional jam, I joined fellow LEVEL0 members and supported the event as part of the organizing staff.',url:'https://app.notion.com/p/de8cea20cae1834ab16c818368f5fd15',link:'See the activity records',color:0xb6a66b}
];
export const artworks=[
 {id:'job',no:'01',title:'Job Battle',subtitle:'IDEA → UNITY',image:'./assets/projects/job-battle-development.png',type:'Prototype in development',tools:'Unity · C# · Photon',description:'I defined the game rules and art direction, then iterated on implementation and debugging with Claude Code + Unity MCP. Inspecting the Animator on a character created at runtime helped us trace and fix recurring animation errors.',detail:'Verified in play mode: controller assignment, Idle playback and entry into Attack.',url:'https://github.com/yumin-beep/3djobbattle',link:'Explore the code',accent:0xd69577},
 {id:'mafia',no:'02',title:'AI Mafia',subtitle:'ONE HUMAN. FIVE AIs.',image:'./assets/projects/ai-mafia-title.png',slides:['./assets/projects/ai-mafia-title.png','./assets/projects/ai-mafia-day-talk.png','./assets/projects/ai-mafia-vote.png'],type:'Team project',tools:'Unity · C# · Ollama · Gemma',description:'One human and five local AI players talk, reason and vote. I developed the game rules, prompts, AI integration and UI. We used Claude during development; the in-game AI runs on Ollama + Gemma.',detail:'Hover to cycle through the actual title, discussion and voting screens.',url:'https://app.notion.com/p/3d2cea20cae181909eb7cb4058ef9894',link:'See how it was made',accent:0x8da2b9},
 {id:'derby',no:'03',title:'Lucky Derby',subtitle:'PLAY IN YOUR BROWSER',image:'./assets/projects/lucky-derby.jpg',type:'Solo project',tools:'JavaScript · Three.js',description:'A browser racing game with transformations, weather and cinematic camera work. Building with Claude, I refined the camera composition to keep the chasing horses in frame.',detail:'You can also find this game in the arcade.',url:'https://yumin-beep.github.io/lucky-derby/',link:'Play the game',accent:0xbab675},
 {id:'night',no:'04',title:'Purification Night',subtitle:'A NIGHT TO SURVIVE',image:'./assets/projects/purification-night-cover.png',animation:'./assets/projects/purification-night-title.gif',type:'Team project',tools:'Unity · C#',description:'For this 2D roguelite, I worked on boss patterns, cutscenes, an infinite map, editor testing tools and build checks.',detail:'Hover over the frame to see the original animated title screen.',url:'https://app.notion.com/p/b97cea20cae182af8f0e01dc73af74ab',link:'Explore the project',accent:0xb0a0bb}
];
export const cabinets=[
 {id:'jam',title:'LEVEL0 GAME JAM',subtitle:'SIX TEAMS / SIX GAMES',image:'./assets/community/gaenojam-outdoor-exhibition.png',description:'Discover six browser games from our very first game jam.',button:'Explore the jam entries',url:'https://itch.io/jam/level0-firstjam-gaenojam',color:0xd28063,glow:0xf2a58a},
 {id:'derby',title:'LUCKY DERBY',subtitle:'BROWSER RACING',image:'./assets/projects/lucky-derby.jpg',description:'Add your names and watch the race unfold. Transformations and weather can change everything.',button:'Play Lucky Derby',url:'https://yumin-beep.github.io/lucky-derby/',embed:'https://yumin-beep.github.io/lucky-derby/',color:0x8b91c8,glow:0xc5afff},
 {id:'cooking',title:'COOKING GENIUS',subtitle:'LOCAL CO-OP / 2 PLAYERS',image:'./assets/community/gaenojam-outdoor-exhibition.png',description:'A local two-player cooking game I helped develop for the first LEVEL0 game jam.',button:'Discover Cooking Genius',url:'https://yuminbeep.itch.io/1',color:0x73a898,glow:0x9fe5c8}
];
